// Builds the panel from src/: each Remotion component (the Look effect and the Reel graphic) is bundled
// into a string constant in src/renderers.ts, then src/Panel.tsx is bundled into ../../panels/<id>/panel.tsx.
// usage: node build.cjs [path/to/esbuild]
const path = require("path");
const fs = require("fs");
const root = __dirname;
const esbuild = require(process.argv[2] || process.env.ESBUILD || "esbuild");
const id = "podcast-hook-captions";
const panelOut = process.env.PANEL_OUT || path.join(root, "..", "..", "panels", id, "panel.tsx");
const name = process.env.PANEL_NAME || "Podcast Hook Captions";

const motion = { lookCode: "Look", reelCode: "Reel" };
let generated = "// Generated by build.cjs from src/motion. Do not edit.\n";
for (const [constName, entry] of Object.entries(motion)) {
  const r = esbuild.buildSync({
    entryPoints: [path.join(root, "src", "motion", entry + ".tsx")],
    bundle: true,
    write: false,
    format: "esm",
    platform: "browser",
    external: ["react", "remotion"],
    jsx: "transform",
    minify: false,
    legalComments: "none",
  });
  generated += "export const " + constName + " = " + JSON.stringify(r.outputFiles[0].text) + ";\n";
}
fs.writeFileSync(path.join(root, "src", "renderers.ts"), generated);

const localized = [
  ["de", "Podcast-Hook-Untertitel"],
  ["en", "Podcast Hook Captions"],
  ["es", "Subtítulos gancho para pódcast"],
  ["fr", "Sous-titres accroche podcast"],
  ["it", "Sottotitoli hook per podcast"],
  ["ja", "ポッドキャスト・フック字幕"],
  ["ko", "Podcast Hook Captions"],
  ["pt", "Legendas de gancho para podcast"],
  ["tr", "Podcast Kanca Altyazıları"],
  ["zh", "播客钩子字幕"],
];
const banner =
  "// @name " + name + "\n" +
  (name.startsWith("__") ? "" : localized.map(([l, n]) => "// @name:" + l + " " + n).join("\n") + "\n") +
  "// @icon captions\n" +
  "// One click turns a podcast Draft into a vertical reel: face-tracked reframe, camera moves, the speaker cut out onto a grid set, kinetic titles, word captions, B-roll cards, music and sound effects.";
esbuild.buildSync({
  entryPoints: [path.join(root, "src", "Panel.tsx")],
  outfile: panelOut,
  bundle: true,
  format: "esm",
  platform: "browser",
  external: ["react"],
  jsx: "transform",
  minify: false,
  legalComments: "none",
  banner: { js: banner },
});
console.log("built", panelOut, fs.statSync(panelOut).size, "bytes");
