// Builds the panel from src/: each Remotion component (the 9:16 frame effect and the captions graphic) is
// bundled into a string constant in src/renderers.ts, then src/Panel.tsx is bundled into panel.tsx.
// usage: node build.cjs [path/to/esbuild]   (PANEL_OUT and PANEL_NAME override the output and the name)
const path = require("path");
const fs = require("fs");
const root = __dirname;
const esbuild = require(process.argv[2] || process.env.ESBUILD || "esbuild");
const panelOut = process.env.PANEL_OUT || path.join(root, "panel.tsx");
const name = process.env.PANEL_NAME || "a16z Style Captions";

const motion = { lookCode: "Look", graphicCode: "Graphic" };
let generated = "// Generated by build.cjs from src/motion. Do not edit.\n";
for (const [constName, entry] of Object.entries(motion)) {
  const r = esbuild.buildSync({
    entryPoints: [path.join(root, "src", "motion", entry + ".tsx")],
    bundle: true,
    write: false,
    format: "esm",
    platform: "browser",
    external: ["react", "remotion"],
    jsx: "transform",
    minify: true,
    legalComments: "none",
  });
  generated += "export const " + constName + " = " + JSON.stringify(r.outputFiles[0].text) + ";\n";
}
fs.writeFileSync(path.join(root, "src", "renderers.ts"), generated);

const localized = [
  ["de", "a16z-Stil-Untertitel"],
  ["en", "a16z Style Captions"],
  ["es", "Subt\u00edtulos estilo a16z"],
  ["fr", "Sous-titres style a16z"],
  ["it", "Sottotitoli stile a16z"],
  ["ja", "a16z\u30b9\u30bf\u30a4\u30eb\u5b57\u5e55"],
  ["ko", "a16z Style Captions"],
  ["pt", "Legendas estilo a16z"],
  ["tr", "a16z Tarz\u0131 Altyaz\u0131lar"],
  ["zh", "a16z \u98ce\u683c\u5b57\u5e55"]
];
const banner =
  "// @name " + name + "\n" +
  (name.startsWith("__") ? "" : localized.map(([l, n]) => "// @name:" + l + " " + n).join("\n") + "\n") +
  "// @icon captions\n" +
  "// One click turns a talking-head Draft into a 9:16 Short in the a16z house style: tightened pauses, speaker framing, editorial captions with lockups and emphasis, keyword cards, a name tag and a music bed.";
esbuild.buildSync({
  entryPoints: [path.join(root, "src", "Panel.tsx")],
  outfile: panelOut,
  bundle: true,
  format: "esm",
  platform: "browser",
  external: ["react"],
  jsx: "transform",
  loader: { ".py": "text" },
  minify: false,
  legalComments: "none",
  banner: { js: banner },
});
console.log("built", panelOut, fs.statSync(panelOut).size, "bytes; renderers", fs.statSync(path.join(root, "src", "renderers.ts")).size, "bytes");
