// Quick local shot score (panel.tsx quick-score block): pure frame maths on synthetic frames always; on real clips
// generated by ffmpeg (static, panning, black fade-in, flash, blurry, scene cut) when ffmpeg is on PATH, driven through
// the block's `io` seam exactly as the host's Runtime.runFFmpeg / FileSystem would be.
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path'), os = require('node:os'), vm = require('node:vm');
const { spawnSync, execFile } = require('node:child_process');

const panel = fs.readFileSync(path.join(__dirname, '..', 'panel.tsx'), 'utf8');
const a = panel.indexOf('// quick-score:start'), b = panel.indexOf('// quick-score:end');
assert.ok(a >= 0 && b > a, 'quick-score block present');
const block = panel.slice(a, b);
assert.ok(!/:\s*(any|string|number|boolean)\b|Promise<|\bas any\b/.test(block), 'the block is plain JS');
assert.ok(!/runShell|child_process|require\(/.test(block), 'no shell, no node');
const ctx = { console, setTimeout, clearTimeout, AbortController, TextDecoder, Uint8Array, Map, Promise, Date, Math, JSON, Object, Number, String, Array, Error };
vm.createContext(ctx);
vm.runInContext(block + '\nthis.Q = { quickScore, quickScoreAll, pickWindowsLocal, qsCandidates, qsFrameStats, qsSceneCuts, qsWindowScores, qsBins, qsFallback, QS_HEAD, QS_W, QS_H, QS_FPS, QS_BIN };', ctx);
const Q = ctx.Q;
const plain = x => JSON.parse(JSON.stringify(x));

// --- Synthetic frames: pure maths ------------------------------------------------------------------------------------
const W = Q.QS_W, H = Q.QS_H, FPS = Q.QS_FPS;
function frame(fn) { const f = new Uint8Array(W * H); for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) f[y * W + x] = Math.max(0, Math.min(255, Math.round(fn(x, y)))); return f; }
function clip(seconds, fnAt) { const n = Math.round(seconds * FPS), out = new Uint8Array(n * W * H); for (let i = 0; i < n; i++) out.set(frame((x, y) => fnAt(i / FPS, x, y)), i * W * H); return out; }
const checker = (t, x, y, shift = 0) => (((Math.floor((x + shift) / 4) + Math.floor(y / 4)) % 2) ? 200 : 60);
{
  const still = Q.qsFrameStats(clip(4, (t, x, y) => checker(t, x, y)), W, H);
  const moving = Q.qsFrameStats(clip(4, (t, x, y) => checker(t, x, y, Math.round(t * 40))), W, H);
  const flat = Q.qsFrameStats(clip(4, () => 128), W, H);
  const mean = (arr, k) => arr.slice(1).reduce((s, f) => s + f[k], 0) / (arr.length - 1);
  assert.ok(mean(still, 'diff') < 0.001, 'a still clip has no motion');
  assert.ok(mean(moving, 'diff') > 0.1, 'a moving pattern has motion');
  assert.ok(mean(still, 'sharp') > 0.1 && mean(flat, 'sharp') < 0.001, 'sharpness: edges vs flat');
  assert.ok(Math.abs(still[0].luma - 130 / 255) < 0.01, 'mean luma');
}
{
  // A black fade-in over the first 1.5 s, then a flash at 4 s, then a hard cut at 6 s.
  const lum = t => (t < 1.5 ? t / 1.5 : 1);
  const bytes = clip(8, (t, x, y) => (Math.abs(t - 4) < 0.07 ? 250 : (t >= 6 ? 255 - checker(t, x, y) * 0.8 : checker(t, x, y, Math.round(t * 6)) * lum(t))));
  const stats = Q.qsFrameStats(bytes, W, H);
  const cuts = plain(Q.qsSceneCuts(stats, FPS, 0));
  assert.ok(cuts.some(t => Math.abs(t - 6) < 0.2), 'the hard cut at 6 s is found: ' + cuts);
  assert.ok(!cuts.some(t => Math.abs(t - 4) < 0.3), 'a flash is not a cut: ' + cuts);
  const bins = plain(Q.qsWindowScores(stats, FPS, 0, Q.qsBins(8, 0, 8), Q.qsSceneCuts(stats, FPS, 0)));
  const at = s => bins.find(w => Math.abs(w.start - s) < 1e-6);
  assert.ok(at(0).flags.black || at(0).flags.fade, 'the first bin is black / fading');
  assert.ok(at(0.5).flags.fade, 'fade-in flagged');
  assert.ok(at(4).flags.flash || at(3.5).flags.flash, 'the flash is flagged');
  assert.ok(at(6).flags.cut || at(5.5).flags.cut, 'the bin starting at the cut is flagged');
  assert.ok(!at(2).flags.black && !at(2).flags.fade && !at(2).flags.flash, 'a clean bin is clean');
  // pickWindowsLocal avoids flagged windows and the clip's head.
  const scores = { rid: 'x', windows: bins, sceneCuts: cuts, duration: 8 };
  for (const role of ['steady', 'montage', 'still']) {
    const picks = plain(Q.pickWindowsLocal(scores, role, 1.5));
    assert.ok(picks.length > 0, role + ' has picks');
    for (const p of picks) {
      assert.ok(p.start >= Q.QS_HEAD - 1e-9 && p.end <= 8 + 1e-9, role + ' window inside the clip after the head');
      assert.ok(!(p.start <= 4 && p.end > 4), role + ' avoids the flash frame (t = 4 s; windows end-exclusive): ' + JSON.stringify(p));
      assert.ok(!(p.start < 5.9 && p.end > 6.1), role + ' avoids the cut: ' + JSON.stringify(p));
      assert.ok(p.start >= 1.5 - 1e-9, role + ' avoids the fade-in: ' + JSON.stringify(p));
      assert.ok(p.score >= 0 && p.score <= 1, 'score in 0-1');
    }
  }
  const cands = plain(Q.qsCandidates(scores, 'montage', 1.67, 4));
  assert.ok(cands.length >= 1 && cands.length <= 4 && cands.every(c => c.t > 0 && c.score >= 0));
  for (let i = 1; i < cands.length; i++) for (let j = 0; j < i; j++) assert.ok(Math.abs(cands[i].t - cands[j].t) >= 1.67 - 1e-9, 'candidates apart');
}
{
  // Roles: 'still' ranks the calmest window first, 'montage' the moving one.
  const bins = [];
  for (let i = 0; i < 12; i++) bins.push({ start: 0.5 + i * 0.5, end: 1 + i * 0.5, motion: i < 6 ? 0.002 : 0.08, sharp: 0.1, luma: 0.45, clipped: 0, flags: { black: false, fade: false, flash: false, blur: false, dark: false, bright: false, cut: false } });
  const sc = { windows: bins, duration: 7 };
  assert.ok(Q.pickWindowsLocal(sc, 'still', 2)[0].start < 3, 'still picks the calm half');
  assert.ok(Q.pickWindowsLocal(sc, 'montage', 2)[0].start >= 3.5, 'montage picks the moving half');
  // Fallback: evenly spaced, unflagged windows from the head; a build still has candidates.
  const fb = plain(Q.qsFallback({ rid: 'r', durationSeconds: 10 }, 0, null));
  assert.equal(fb.fallback, true); assert.equal(fb.windows[0].start, Q.QS_HEAD);
  assert.ok(Q.pickWindowsLocal(fb, 'montage', 1.67).length > 5);
}

// --- No host: quickScore falls back, never throws; an aborted signal throws -------------------------------------------
(async () => {
  const none = await Q.quickScore({ rid: 'a', path: '/x.mp4', durationSeconds: 12 }, { io: {}, dataDir: '/tmp' });
  assert.equal(none.fallback, true);
  const failing = { runFFmpeg: async () => { throw new Error('ffmpeg failed'); }, readBytes: async () => null, join: (...p) => p.join('/'), remove: async () => {} };
  const r = await Q.quickScore({ rid: 'b', path: '/x.mp4', durationSeconds: 12 }, { io: failing, dataDir: '/tmp' });
  assert.equal(r.fallback, true, 'an ffmpeg failure falls back');
  const ac = new AbortController(); ac.abort();
  await assert.rejects(Q.quickScore({ rid: 'c', path: '/x.mp4', durationSeconds: 12 }, { io: failing, dataDir: '/tmp', signal: ac.signal }), /cancelled/);

  // --- Real clips through ffmpeg (skipped without ffmpeg) -----------------------------------------------------------
  const probe = spawnSync('ffmpeg', ['-version'], { encoding: 'utf8' });
  if (probe.status !== 0) { console.log(JSON.stringify({ quickScore: 'ok', ffmpeg: 'skipped' })); return; }
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'qs-'));
  const ff = (args) => { const r = spawnSync('ffmpeg', ['-v', 'error', '-y', ...args], { encoding: 'utf8' }); if (r.status !== 0) throw Error(r.stderr); };
  const src = 'testsrc2=size=640x360:rate=30';
  ff(['-f', 'lavfi', '-i', src, '-frames:v', '1', path.join(dir, 'still.png')]);
  ff(['-loop', '1', '-i', path.join(dir, 'still.png'), '-t', '8', '-r', '30', '-pix_fmt', 'yuv420p', path.join(dir, 'static.mp4')]);
  ff(['-f', 'lavfi', '-i', 'mandelbrot=size=1280x360:rate=30', '-t', '8', '-vf', "crop=640:360:'min(t*80,640)':0", '-pix_fmt', 'yuv420p', path.join(dir, 'pan.mp4')]);
  ff(['-f', 'lavfi', '-i', src, '-t', '8', '-vf', 'fade=t=in:st=0:d=1.5', '-pix_fmt', 'yuv420p', path.join(dir, 'fadein.mp4')]);
  ff(['-f', 'lavfi', '-i', src, '-t', '8', '-vf', "drawbox=x=0:y=0:w=iw:h=ih:color=white:t=fill:enable='between(t,4,4.1)'", '-pix_fmt', 'yuv420p', path.join(dir, 'flash.mp4')]);
  ff(['-f', 'lavfi', '-i', src, '-t', '8', '-vf', 'boxblur=20:2', '-pix_fmt', 'yuv420p', path.join(dir, 'blurry.mp4')]);
  ff(['-f', 'lavfi', '-i', src + ':d=4', '-f', 'lavfi', '-i', 'mandelbrot=size=640x360:rate=30', '-filter_complex', '[1]trim=duration=4,setpts=PTS-STARTPTS[b];[0][b]concat=n=2:v=1[v]', '-map', '[v]', '-pix_fmt', 'yuv420p', path.join(dir, 'cut.mp4')]);
  const io = {
    runFFmpeg: (args, signal) => new Promise((res, rej) => { const p = execFile('ffmpeg', args, (e) => (e ? rej(e) : res({}))); if (signal) signal.addEventListener('abort', () => p.kill()); }),
    readBytes: async (p) => new Uint8Array(fs.readFileSync(p)), remove: async (p) => { try { fs.unlinkSync(p); } catch {} },
    join: (...p) => path.join(...p), mkdir: (d) => fs.mkdirSync(d, { recursive: true }), mtimeMs: (p) => fs.statSync(p).mtimeMs,
    readText: async (p) => fs.readFileSync(p, 'utf8'), writeText: async (p, t) => fs.writeFileSync(p, t),
  };
  const data = path.join(dir, 'data');
  const run = (name) => Q.quickScore({ rid: name, path: path.join(dir, name + '.mp4'), durationSeconds: 8 }, { io, dataDir: data, budgetMs: 20000 }).then(plain);
  const t0 = Date.now();
  const [st, pan, fade, flash, blur, cut] = await Promise.all(['static', 'pan', 'fadein', 'flash', 'blurry', 'cut'].map(run));
  const wall = Date.now() - t0;
  const avg = (r, k) => r.windows.reduce((s, w) => s + w[k], 0) / r.windows.length;
  for (const r of [st, pan, fade, flash, blur, cut]) assert.equal(r.fallback, false, r.rid + ' decoded');
  assert.ok(avg(st, 'motion') < 0.005 && avg(pan, 'motion') > 0.02, 'static vs panning motion: ' + avg(st, 'motion') + ' / ' + avg(pan, 'motion'));
  assert.ok(avg(blur, 'sharp') < 0.5 * avg(st, 'sharp'), 'blurry is less sharp');
  assert.ok(fade.windows[0].flags.fade || fade.windows[0].flags.black, 'fade-in flagged at the head');
  assert.ok(flash.windows.some(w => w.flags.flash && w.start <= 4.1 && w.end >= 4), 'flash flagged near 4 s');
  assert.ok(cut.sceneCuts.some(t => Math.abs(t - 4) < 0.3), 'scene cut near 4 s: ' + cut.sceneCuts);
  for (const p of Q.pickWindowsLocal(fade, 'steady', 1.67)) assert.ok(p.start >= 1.4, 'picks skip the fade-in');
  for (const p of Q.pickWindowsLocal(flash, 'montage', 1.67)) assert.ok(!(p.start < 4.1 && p.end > 4), 'picks skip the flash');
  assert.ok(Q.pickWindowsLocal(pan, 'montage', 1.67)[0].score > Q.pickWindowsLocal(st, 'montage', 1.67)[0].score, 'montage prefers motion');
  // Cache: a second run of the same file is read from the data folder.
  const again = plain(await Q.quickScore({ rid: 'static', path: path.join(dir, 'static.mp4'), durationSeconds: 8 }, { io, dataDir: data }));
  assert.equal(again.cached, true);
  assert.deepEqual(again.windows, st.windows);
  // No temporary files left behind.
  assert.deepEqual(fs.readdirSync(path.join(data, 'quick-score')).filter(f => !f.endsWith('.json')), []);
  // quickScoreAll: bounded concurrency with progress, and a cancelled run throws.
  const seen = [];
  const all = await Q.quickScoreAll(['pan', 'flash', 'blurry'].map(n => ({ rid: n + '-2', path: path.join(dir, n + '.mp4'), durationSeconds: 8 })), { io, dataDir: data, concurrency: 2, onProgress: p => seen.push(p.done) });
  assert.equal(all.size, 3); assert.deepEqual(seen, [1, 2, 3]);
  const ac2 = new AbortController(); ac2.abort();
  await assert.rejects(Q.quickScoreAll([{ rid: 'z', path: path.join(dir, 'pan.mp4'), durationSeconds: 8 }], { io, dataDir: data, signal: ac2.signal }), /cancelled/);
  fs.rmSync(dir, { recursive: true, force: true });
  console.log(JSON.stringify({ quickScore: 'ok', ffmpeg: 'ran', clips: 6, wallMs: wall, perClipMs: [st, pan, fade, flash, blur, cut].map(r => r.ms) }));
})().catch((e) => { console.error(e); process.exit(1); });
