#!/usr/bin/env python3
"""
Engine of the Selects app "Vox \uc2a4\ud0c0\uc77c \uc124\uba85 \uc601\uc0c1" (vox-explainer).

A source (a link or pasted text) and a target length become the parts of a
Vox-style paper-collage explainer. Media is generated by Selects itself (the
panel submits the requests this engine writes, and Selects bills its credits);
the engine does the local work: reading the source, checking the AI script,
free-licence portraits, narration timing, contact sheets, the Ken Burns
fallback and the Draft plan.

Standard library only; runs on macOS system Python 3.9+. Every command ends in
seconds and keeps its state in the job folder.

  engine.py check
  engine.py fetch <job>                      input in job.json -> article.json
  engine.py validate <job>                   plan.json from the panel's AI step -> normalised plan
  engine.py portraits <job>                  Wikimedia Commons portraits (public domain / CC BY / CC BY-SA)
  engine.py requests <job> narration|keyframes|clips|music [shot,shot] [--attempt N]
  engine.py timeline <job>                   narration timing from the delivered audio -> timeline.json
  engine.py sheet <job> [shot,shot]          numbered contact sheet(s) for the AI image check
  engine.py kenburns <job> shot,shot         pan-and-zoom clips where motion generation failed
  engine.py assembly <job>                   selects.json: what the panel places in the Draft

Files the panel receives from Selects are listed in gen.json (written by the panel):
{"narr:1": {"path": ...}, "kf:1a": {"path": ..., "attempt": 1}, "clip:1a": {...}, "music": {...}}.

The look is the one validated on 2026-09-30. Lines marked LESSON encode what the
first manual run got wrong.
"""
import html
import json
import math
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

VERSION = "2.1.0"

# ---- Selects generation models (ids copied from Selects' model discovery, 2026-09-30) -----
MODEL = {
    "t2i": "model_v1_ZmFsLWFpL25hbm8tYmFuYW5hLTI",                          # Nano Banana 2
    "edit": "model_v1_ZmFsLWFpL25hbm8tYmFuYW5hLTIvZWRpdA",                  # Nano Banana 2 edit
    "i2v": "model_v1_ZmFsLWFpL2tsaW5nLXZpZGVvL3YzL3Byby9pbWFnZS10by12aWRlbw",  # Kling v3 Pro
    "tts": "model_v1_ZmFsLWFpL2VsZXZlbmxhYnMvdHRzL2VsZXZlbi12Mw",           # ElevenLabs v3
    "music": "model_v1_ZmFsLWFpL2VsZXZlbmxhYnMvbXVzaWM",                    # ElevenLabs Music
}

# ---- Fixed look and sound -----------------------------------------------------------------
W, H, FPS = 1080, 1920, 24
LEAD, TAIL, END_HOLD = 0.15, 0.35, 2.3          # seconds around each beat's narration; closing hold
VOICE = "Alice"
MUSIC_PROMPT = ("modern news explainer underscore, tense pulsing synth bass, crisp ticking percussion, "
                "light piano stabs, confident and curious, steady build, no big drops, instrumental, no vocals")

# Output language follows the source. rate = speech units per second for voice "Alice"
# (CJK: characters; Latin: syllables); wps = words per second for the script length budget.
# Measured: Korean 5.35 syllables/s (2026-09-30); English 1.96 words/s = 3.94 syllables/s (2026-10-01).
# The other languages are scaled from English and are estimates until a run measures them.
LANG = {
    "ko": {"name": "Korean", "cjk": True, "rate": 5.35, "cap": 16, "cap_max": 18, "head": 12, "head_max": 16,
           "style": "formal \ud569\ub2c8\ub2e4\uccb4 news tone", "photos": "\uc778\ubb3c \uc0ac\uc9c4", "pd": "\ud37c\ube14\ub9ad \ub3c4\uba54\uc778", "source": "\ucd9c\ucc98"},
    "ja": {"name": "Japanese", "cjk": True, "rate": 7.0, "cap": 16, "cap_max": 18, "head": 12, "head_max": 16,
           "style": "polite です・ます news tone", "photos": "人物写真", "pd": "パブリックドメイン", "source": "出典"},
    "zh": {"name": "Chinese (in the source's script)", "cjk": True, "rate": 4.5, "cap": 14, "cap_max": 16, "head": 10,
           "head_max": 14, "style": "neutral news tone", "photos": "人物照片", "pd": "公有领域", "source": "来源"},
    "en": {"name": "English", "cjk": False, "rate": 4.0, "wps": 1.95, "cap": 32, "cap_max": 36, "head": 24, "head_max": 28,
           "style": "neutral news tone", "photos": "Photos", "pd": "public domain", "source": "Source"},
    "de": {"name": "German", "cjk": False, "rate": 3.8, "wps": 1.65, "cap": 32, "cap_max": 36, "head": 24, "head_max": 28,
           "style": "neutral news tone", "photos": "Fotos", "pd": "gemeinfrei", "source": "Quelle"},
    "es": {"name": "Spanish", "cjk": False, "rate": 5.0, "wps": 2.1, "cap": 32, "cap_max": 36, "head": 24, "head_max": 28,
           "style": "neutral news tone", "photos": "Fotos", "pd": "dominio público", "source": "Fuente"},
    "fr": {"name": "French", "cjk": False, "rate": 4.6, "wps": 2.1, "cap": 32, "cap_max": 36, "head": 24, "head_max": 28,
           "style": "neutral news tone", "photos": "Photos", "pd": "domaine public", "source": "Source"},
    "it": {"name": "Italian", "cjk": False, "rate": 4.8, "wps": 2.1, "cap": 32, "cap_max": 36, "head": 24, "head_max": 28,
           "style": "neutral news tone", "photos": "Foto", "pd": "pubblico dominio", "source": "Fonte"},
    "pt": {"name": "Portuguese", "cjk": False, "rate": 4.6, "wps": 2.0, "cap": 32, "cap_max": 36, "head": 24, "head_max": 28,
           "style": "neutral news tone", "photos": "Fotos", "pd": "domínio público", "source": "Fonte"},
    "tr": {"name": "Turkish", "cjk": False, "rate": 4.4, "wps": 1.65, "cap": 32, "cap_max": 36, "head": 24, "head_max": 28,
           "style": "neutral news tone", "photos": "Fotoğraflar", "pd": "kamu malı", "source": "Kaynak"},
}
STOPWORDS = {
    "en": "the and of to in is that for on with as was by it from at are be this have has said".split(),
    "de": "der die und das ist nicht mit den von zu ein eine auf für sich dem des im auch wird".split(),
    "es": "el la de que y en los las del se por un una con para es su al lo como más".split(),
    "fr": "le la les de des et est une un du en dans que pour sur au par pas plus avec qui".split(),
    "it": "il la di che e è un una per del della con non sono le gli nel alla anche più".split(),
    "pt": "o a de que e do da em um uma para com não os as dos das no na por mais".split(),
    "tr": "ve bir bu da de için ile olarak çok daha gibi ama olan en ne değil kadar sonra".split(),
}

THEME = {  # vox-director theme "soviet-constructivist"
    "idiom": "Russian Constructivist photomontage, bold diagonal geometry",
    "palette": "red, black, cream",
    "finish": "letterpress, newsprint",
}
MECHANICS = (
    "Clearly layered hand-cut paper cut-outs with visible torn and scissor-cut edges, tape "
    "corners and soft real paper drop shadows, on a bold flat {bg} paper background. Halftone "
    "print dots, newspaper-clipping scraps, paper-stencil shapes, aged paper texture, slight "
    "print misregistration, scattered geometric paper accents (triangles, circles, zigzags, "
    "washi tape). Figures are PRINTED / illustrated cut-outs, NOT CGI, NOT a 3D render — keep "
    "print grain and paper imperfections. High-contrast, punchy, tactile, hand-assembled."
)
# LESSON: the image model invents realistic people (even a named country's leader) in shots that
# have none, and once put the wrong country stamp under the wrong person.
NO_PEOPLE = (" NO people, NO faces, NO human figures and NO photographs of people anywhere "
             "(a paper hand, or faceless paper silhouettes, only if the SCENE asks for them). A named "
             "country, company or institution is shown by its label, flag or object only — never add a "
             "portrait, photo or drawing of a leader, politician or any other person for it.")
FACE_GUARD = (" Halftone dots and print textures live on the BACKGROUND and paper only, never on "
              "faces. The ONLY people in the image are the attached ones — no extra people. Every "
              "face gets the same photographic treatment at a similar scale; never draw any face "
              "as a cartoon or caricature. Every label named next to a person sits right next to "
              "that person.")
TEXT_GUARD = (" Newspaper scraps carry completely UNREADABLE blurred micro-text. The ONLY readable "
              "words in the image are the ones quoted in the SCENE, spelled exactly with no added "
              "punctuation; no other captions, logos or watermarks.")
# LESSON: the headline covered a title banner drawn into the art; captions covered labels.
LAYOUT_GUARD = (" Leave the top 18% and the bottom 12% of the frame as calm plain background (a "
                "headline and subtitles are added later); keep every person and every quoted word "
                "between those bands. No big title banner anywhere.")
FACE_LOCK = (
    "The attached photos are real people ({who}). Cut each person's face and hair out as a "
    "PHOTOGRAPHIC sticker with a torn white paper border and place them in the scene — keep "
    "each facial identity, features and expression from their photo pixel-faithful; do not "
    "redraw, repaint, swap or stylize any face; NO halftone dots, print texture or ink treatment "
    "on faces or hair. All poses and gestures are expressed by the bodies only. From the neck "
    "down each body is a hand-drawn paper-doll illustration jointed like a vintage paper puppet "
    "with visible cut edges, FULLY CLOTHED ({clothes}). "
)
FREEZE = ("FREEZE every photographic face sticker — frozen layers, pixel-identical to the still "
          "for the entire duration; never redraw, warp, re-time or animate the faces; the "
          "paper-doll bodies may shift slightly at their joints. ")
CAMERA = {
    "static": "a locked-off static camera (no camera move)",
    "push_in": "one very slow smooth push-in (uniform scale-up, Ken-Burns)",
    "pull_out": "one slow smooth pull-out (uniform scale-down) revealing the full scene",
    "pan": "one slow horizontal pan across the frame (flat translate, no perspective shift)",
    "parallax": "a gentle multi-layer parallax drift (paper layers moving at slightly different "
                "speeds), the camera otherwise steady",
}
# LESSON: a tilt carried two faces up under the headline; people shots keep the camera near centre.
CAST_CAMERAS = ("push_in", "parallax", "static")
AMPLITUDE = {"calm": "subtle, restrained amplitude",
             "punchy": "lively, energetic amplitude with clear, bold movement"}
PALETTE_BG = ["deep navy blue", "cream white with bold red accents", "bright mustard yellow",
              "deep crimson red", "cool slate teal", "pale mint green", "sky blue", "warm cream"]

UA_BROWSER = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
              "(KHTML, like Gecko) Chrome/128.0 Safari/537.36")
UA_API = "SelectsVoxExplainer/2.0 (+https://tryselects.com)"


class EngineError(Exception):
    pass


# ---- Small helpers ---------------------------------------------------------------------------
def out(obj):
    sys.stdout.write(json.dumps(obj, ensure_ascii=False))
    sys.stdout.flush()


def load(path, default=None):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return default


def save(path, obj):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=1)
    os.replace(tmp, path)


def http_get(url, ua, timeout=40):
    req = urllib.request.Request(url, headers={"User-Agent": ua, "Accept-Language": "ko,en;q=0.8"})
    last = None
    for attempt in range(3):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return r.status, r.read()
        except urllib.error.HTTPError as e:
            return e.code, e.read()
        except (urllib.error.URLError, TimeoutError, OSError) as e:
            last = e
            time.sleep(1.5 * (attempt + 1))
    raise EngineError("NETWORK %s" % last)


def get_json(url):
    code, b = http_get(url, UA_API)
    try:
        return json.loads(b.decode("utf-8", "replace"))
    except ValueError:
        return {}


def find_tool(name):
    cands = ["/Applications/%s.app/Contents/Resources/app.asar.unpacked/dist/bin/%s" % (app, name)
             for app in ("Selects", "Selects Staging", "Selects Delta", "Selects Dev")]
    cands += ["/opt/homebrew/bin/" + name, "/usr/local/bin/" + name, "/usr/bin/" + name]
    for c in cands:
        if os.path.isfile(c) and os.access(c, os.X_OK):
            return c
    return None


def media_duration(path):
    r = subprocess.run([find_tool("ffprobe"), "-v", "error", "-show_entries", "format=duration", "-of",
                        "csv=p=0", path], capture_output=True, text=True)
    try:
        return float(r.stdout.strip())
    except ValueError:
        raise EngineError("cannot read duration: %s" % path)


def strip_tags(s):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", s or ""))).strip()


def norm_words(text):
    return [re.sub(r"[.,!?'\"“”‘’·…()。、，！？「」]", "", w) for w in text.split()]


# ---- Language ----------------------------------------------------------------------------------
def detect_lang(text):
    t = text[:5000]
    if len(re.findall(r"[\uac00-\ud7a3]", t)) > 20:
        return "ko"
    if len(re.findall(r"[぀-ヿ]", t)) > 20:
        return "ja"
    if len(re.findall(r"[一-鿿]", t)) > 40:
        return "zh"
    words = re.findall(r"[a-zà-ÿğüşıöç]+", t.lower())
    scores = {k: sum(1 for w in words if w in set(v)) for k, v in STOPWORDS.items()}
    best = max(scores, key=scores.get)
    return best if scores[best] > 3 else "en"


def word_weight(w, lang):
    """Speech units of one written word: characters for CJK, a syllable estimate for Latin."""
    digits = len(re.findall(r"\d", w))
    if LANG[lang]["cjk"]:
        cjk = len(re.findall(r"[\uac00-\ud7a3぀-ヿ一-鿿]", w))
        latin = re.findall(r"[A-Za-z]+", w)
        return max(0.5, cjk + digits * 1.5 + sum(len(x) * (1.5 if x.isupper() else 0.5) for x in latin))
    groups = len(re.findall(r"[aeiouyàáâäãåèéêëìíîïòóôöõùúûüıAEIOUY]+", w))
    caps = len(w) if re.fullmatch(r"[A-Z]{2,5}", re.sub(r"\W", "", w)) else 0   # acronyms read letter by letter
    return max(1.0, groups, caps) + digits * 1.2


def speech_seconds(text, lang):
    return sum(word_weight(w, lang) for w in text.split()) / LANG[lang]["rate"]


def budget(target, lang):
    nb = max(3, min(10, int(round(target / 8.0))))
    speak = max(8.0, target - END_HOLD - nb * (LEAD + TAIL))
    L = LANG[lang]
    if L["cjk"]:
        return {"beats": nb, "unit": "characters" if lang != "ko" else "syllables", "count": int(round(speak * L["rate"]))}
    return {"beats": nb, "unit": "words", "count": int(round(speak * L["wps"]))}


# ---- Job folder ----------------------------------------------------------------------------------
class Job:
    def __init__(self, path):
        self.dir = path
        self.path = os.path.join(path, "job.json")
        self.data = load(self.path)
        if not self.data:
            raise EngineError("job.json missing in %s" % path)
        self.id = self.data["id"]

    def p(self, *parts):
        d = os.path.join(self.dir, *parts[:-1])
        os.makedirs(d, exist_ok=True)
        return os.path.join(d, parts[-1])

    def save(self):
        self.data["updated"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        save(self.path, self.data)

    def plan(self):
        p = load(os.path.join(self.dir, "plan.json"))
        if not p:
            raise EngineError("plan.json missing")
        return p

    def gen(self):
        return load(os.path.join(self.dir, "gen.json"), {}) or {}

    def file(self, key):
        g = self.gen().get(key) or {}
        path = g.get("path")
        return path if path and os.path.exists(path) else None


def shots_of(plan):
    for b in plan["beats"]:
        for s in b["shots"]:
            yield b, s


# ---- fetch -------------------------------------------------------------------------------------
def meta(s, prop):
    m = re.search(r'<meta[^>]+(?:property|name)=["\']%s["\'][^>]+content=["\']([^"\']*)' % re.escape(prop), s)
    if not m:
        m = re.search(r'<meta[^>]+content=["\']([^"\']*)["\'][^>]+(?:property|name)=["\']%s["\']' % re.escape(prop), s)
    return html.unescape(m.group(1)).strip() if m else ""


def korean_name(n):
    """Arc stores Korean bylines as 'given family' ('\uad6d\ud76c \ubc15'); print them the Korean way ('\ubc15\uad6d\ud76c')."""
    m = re.match(r"^([\uac00-\ud7a3]{1,3}) ([\uac00-\ud7a3]{1,2})$", (n or "").strip())
    return m.group(2) + m.group(1) if m else n


def extract_article(url, s):
    title = meta(s, "og:title") or strip_tags((re.search(r"<title>(.*?)</title>", s, re.S) or [None, ""])[1])
    art = {"url": url, "title": title, "subtitle": "", "description": meta(s, "og:description"),
           "source": meta(s, "og:site_name"), "date": meta(s, "article:published_time"),
           "byline": meta(s, "author") or meta(s, "dable:author"), "body": "", "method": ""}
    m = re.search(r"Fusion\.globalContent\s*=\s*(\{.*?\});\s*Fusion\.", s, re.S)   # Arc XP (Chosun and others)
    if m:
        try:
            d = json.loads(m.group(1))
            paras = [strip_tags(e.get("content", "")) for e in d.get("content_elements", []) if e.get("type") == "text"]
            if paras:
                art["body"] = "\n".join(p for p in paras if p)
                art["title"] = (d.get("headlines") or {}).get("basic") or art["title"]
                art["subtitle"] = strip_tags(re.sub(r"<br\s*/?>", " / ", (d.get("subheadlines") or {}).get("basic") or ""))
                by = [korean_name(c.get("name")) for c in (d.get("credits") or {}).get("by", []) if c.get("name")]
                if by:
                    art["byline"] = ", ".join(by)
                art["date"] = d.get("display_date") or d.get("first_publish_date") or art["date"]
                art["method"] = "arc"
        except ValueError:
            pass
    for blk in re.findall(r'<script[^>]+application/ld\+json[^>]*>(.*?)</script>', s, re.S):   # JSON-LD
        try:
            d = json.loads(blk.strip())
        except ValueError:
            continue
        items = d if isinstance(d, list) else d.get("@graph", [d]) if isinstance(d, dict) else []
        for it in items:
            if not (isinstance(it, dict) and "Article" in str(it.get("@type", ""))):
                continue
            pub = it.get("publisher")
            if isinstance(pub, dict) and pub.get("name") and not art["source"]:
                art["source"] = pub["name"]
            art["date"] = art["date"] or it.get("datePublished") or ""
            art["description"] = art["description"] or strip_tags(it.get("description") or "")
            a = it.get("author")
            names = [x.get("name", "") for x in (a if isinstance(a, list) else [a]) if isinstance(x, dict)]
            if any(names) and not art["byline"]:
                art["byline"] = ", ".join(n for n in names if n)
            if it.get("articleBody") and not art["body"]:
                art["body"] = strip_tags(it["articleBody"])
                art["title"] = it.get("headline") or art["title"]
                art["method"] = "jsonld"
    if not art["body"]:
        scope = (re.search(r"<article[^>]*>(.*?)</article>", s, re.S) or [None, s])[1]
        paras = [strip_tags(p) for p in re.findall(r"<p[^>]*>(.*?)</p>", scope, re.S)]
        art["body"] = "\n".join(p for p in paras if len(p) > 40 and not re.match(r"^(Share|Save|Advertisement|Related)\b", p))
        art["method"] = "paragraphs"
    art["body"] = art["body"][:20000]
    art["lang"] = detect_lang(art["title"] + " " + art["body"])
    return art


def cmd_fetch(job):
    inp = job.data["input"]
    if inp.get("kind") == "text":
        text = inp.get("text", "").strip()
        if len(text) < 80:
            raise EngineError("TEXT_TOO_SHORT")
        lines = [l.strip() for l in text.splitlines() if l.strip()]
        art = {"url": "", "title": lines[0][:120], "subtitle": "", "description": "", "source": "", "date": "",
               "byline": "", "body": text[:20000], "method": "text", "lang": detect_lang(text)}
    else:
        url = inp.get("url", "").strip()
        code, b = http_get(url, UA_BROWSER, timeout=30)
        if code >= 300:
            raise EngineError("FETCH_FAILED")
        art = extract_article(url, b.decode("utf-8", "replace"))
        if len(art["body"]) < 200:
            raise EngineError("NO_TEXT")
    save(job.p("article.json"), art)
    job.data.update(stage="fetched", lang=art["lang"])
    job.save()
    out({"ok": True, "title": art["title"], "chars": len(art["body"]), "method": art["method"], "lang": art["lang"],
         "language": LANG[art["lang"]]["name"], "style": LANG[art["lang"]]["style"],
         "sourceLabel": LANG[art["lang"]]["source"], "budget": budget(job.data.get("target", 55), art["lang"]),
         "captionChars": LANG[art["lang"]]["cap"], "headlineChars": LANG[art["lang"]]["head"]})


# ---- validate ------------------------------------------------------------------------------------
def auto_captions(text, maxc):
    lines, cur = [], []
    for w in text.split():
        if cur and len(" ".join(cur + [w])) > maxc:
            lines.append(" ".join(cur))
            cur = []
        cur.append(w)
        if re.search(r"[.,!?。、，！？]$", w) and len(" ".join(cur)) >= maxc * 0.4:
            lines.append(" ".join(cur))
            cur = []
    if cur:
        lines.append(" ".join(cur))
    return [l.rstrip(",.") for l in lines]


def cmd_validate(job):
    plan = job.plan()
    lang = job.data.get("lang", "en")
    L = LANG[lang]
    warn, err = [], []
    cast = {}
    for c in plan.get("cast") or []:
        key = re.sub(r"[^a-z0-9_]", "", str(c.get("key", "")).lower())
        if key and c.get("name"):
            cast[key] = {"key": key, "name": str(c["name"]), "wiki": str(c.get("wiki") or c["name"]),
                         "wardrobe": str(c.get("wardrobe") or "a dark suit and white shirt")}
    beats, prev_cam = [], None
    for bi, b in enumerate(plan.get("beats") or []):
        narr = re.sub(r"\s+", " ", str(b.get("narration", ""))).strip()
        if not narr:
            continue
        title = str(b.get("headline") or b.get("title_ko") or b.get("title") or "").strip()[:L["head_max"]]
        caps = [str(x).strip() for x in (b.get("captions") or []) if str(x).strip()]
        # LESSON: automatic line breaks split names ('\uc820\uc2a8 / \ud669'); the AI breaks lines, this checks them
        if "".join(norm_words(" ".join(caps))) != "".join(norm_words(narr)) or any(len(c) > L["cap_max"] for c in caps):
            if caps:
                warn.append("beat %d captions re-broken" % (bi + 1))
            caps = auto_captions(narr, L["cap"])
        shots = []
        for s in (b.get("shots") or [])[:2]:
            scene = str(s.get("scene", "")).strip()
            if not scene:
                continue
            sc = [k for k in [re.sub(r"[^a-z0-9_]", "", str(x).lower()) for x in (s.get("cast") or [])] if k in cast][:4]
            cam = str(s.get("camera") or s.get("camera_move") or "push_in")
            cam = cam if cam in CAMERA else "push_in"
            if sc and cam not in CAST_CAMERAS:
                cam = "parallax"
            if cam == prev_cam:  # LESSON: neighbouring shots never repeat a camera move
                cam = [c for c in (CAST_CAMERAS if sc else ("push_in", "parallax", "pan", "pull_out")) if c != prev_cam][0]
            prev_cam = cam
            shots.append({"id": "%d%s" % (len(beats) + 1, "ab"[len(shots)]), "scene": scene,
                          "motion": str(s.get("element_motion") or s.get("motion") or
                                        "one or two paper elements slide gently; halftone dots pulse"),
                          "camera": cam, "cast": sc, "has_text": bool(re.search(r"['\"“‘]", scene))})
        if not shots:
            err.append("beat %d has no usable shot" % (bi + 1))
            continue
        words, cut = norm_words(narr), None
        if len(shots) == 2:
            cw = norm_words(str(b.get("cut_word") or ""))
            idx = [i for i, w in enumerate(words) if cw and w == cw[0] and i > 0]
            cut = idx[0] if idx else None
            if cut is None:   # the middle of the narration by speech length
                total, acc = speech_seconds(narr, lang), 0.0
                for i, w in enumerate(narr.split()):
                    acc += word_weight(w, lang) / L["rate"]
                    if acc >= total / 2 and 0 < i + 1 < len(words):
                        cut = i + 1
                        break
            parts = narr.split()
            if (cut is None or speech_seconds(" ".join(parts[:cut]), lang) < 1.5
                    or speech_seconds(" ".join(parts[cut:]), lang) < 1.5):
                shots, cut = shots[:1], None
        beats.append({"n": len(beats) + 1, "title": title, "narration": narr, "captions": caps,
                      "bg": str(b.get("bg") or PALETTE_BG[len(beats) % len(PALETTE_BG)]),
                      "shots": shots, "cut_index": cut})
    if not beats:
        err.append("no beats")
    else:
        beats[-1]["shots"][-1]["camera"] = "static"   # the payoff lands on a still frame
    used = {k for b in beats for s in b["shots"] for k in s["cast"]}
    norm = {"version": VERSION, "lang": lang, "title": str(plan.get("title") or "")[:60],
            "source_line": str(plan.get("source_line") or "")[:140],
            "cast": [cast[k] for k in cast if k in used], "beats": beats}
    save(job.p("plan.json"), norm)
    job.data["stage"] = "planned" if not err else "plan_error"
    job.save()
    shots_n = sum(len(b["shots"]) for b in beats)
    est = sum(LEAD + speech_seconds(b["narration"], lang) + TAIL for b in beats) + END_HOLD
    out({"ok": not err, "errors": err, "warnings": warn, "lang": lang, "seconds": round(est, 1),
         "beats": len(beats), "shots": shots_n, "people": [c["name"] for c in norm["cast"]]})


# ---- portraits ---------------------------------------------------------------------------------
LICENSE_OK = re.compile(r"public domain|^pd\b|cc0|cc[- ]by(-sa)?[- ]?\d", re.I)
LICENSE_BAD = re.compile(r"\bnc\b|\bnd\b|non-?commercial|no ?deriv", re.I)


def wiki_portrait(title, dest):
    d = get_json("https://en.wikipedia.org/w/api.php?" + urllib.parse.urlencode(
        {"action": "query", "prop": "pageimages", "piprop": "original|name", "titles": title, "format": "json",
         "redirects": 1}))
    pages = list(((d or {}).get("query") or {}).get("pages", {}).values())
    name = pages[0].get("pageimage") if pages else None
    if not name:
        return {"ok": False, "error": "no lead image"}
    m = get_json("https://commons.wikimedia.org/w/api.php?" + urllib.parse.urlencode(
        {"action": "query", "titles": "File:" + name, "prop": "imageinfo", "iiprop": "extmetadata", "format": "json"}))
    cp = list(((m or {}).get("query") or {}).get("pages", {}).values())
    em = ((cp[0].get("imageinfo") or [{}])[0].get("extmetadata") or {}) if cp else {}
    lic = (em.get("LicenseShortName") or {}).get("value", "")
    if not LICENSE_OK.search(lic) or LICENSE_BAD.search(lic):
        return {"ok": False, "file": name, "license": lic}
    artist = re.sub(r"^(Photographer|Photo|Author)\s*:\s*", "", strip_tags((em.get("Artist") or {}).get("value", "")), flags=re.I)[:60]
    code, b = http_get("https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/" +
                       urllib.parse.quote(name) + "&width=900", UA_API, timeout=60)
    if code >= 300 or not b:
        return {"ok": False, "file": name, "error": "download %s" % code}
    with open(dest, "wb") as f:
        f.write(b)
    return {"ok": True, "file": name, "license": lic, "artist": artist}


def cmd_portraits(job):
    plan = job.plan()
    portraits = job.data.setdefault("portraits", {})
    for c in plan["cast"]:
        if c["key"] not in portraits:
            try:
                r = wiki_portrait(c["wiki"], job.p("portraits", "%s.jpg" % c["key"]))
            except EngineError as e:
                r = {"ok": False, "error": str(e)}
            portraits[c["key"]] = dict(r, name=c["name"])
    # A person without a free photo becomes a faceless paper silhouette with a name card; the image
    # model must never draw a real person's likeness from memory.
    missing = {k for k, v in portraits.items() if not v.get("ok")}
    for _, s in shots_of(plan):
        for k in [k for k in s["cast"] if k in missing]:
            name = next(c["name"] for c in plan["cast"] if c["key"] == k)
            s["scene"] = s["scene"].replace(name, "a faceless paper silhouette with a name card '%s'" % name.split()[-1].upper())
            s["cast"].remove(k)
    save(job.p("plan.json"), plan)
    job.data["stage"] = "portraits"
    job.save()
    out({"ok": True, "found": sorted(k for k in portraits if k not in missing),
         "missing": [portraits[k]["name"] for k in sorted(missing)]})


# ---- generation requests for the panel -------------------------------------------------------------
def keyframe_prompt(plan, beat, shot):
    world = ("%s Palette: %s. %s Print finish: %s. SCENE (as layered paper cut-outs): %s. No big headline in "
             "this shot (a small accent only); it is a cut-in detail. Aspect ratio 9:16."
             % (THEME["idiom"], THEME["palette"], MECHANICS.format(bg=beat["bg"]), THEME["finish"], shot["scene"]))
    if shot["cast"]:
        cast = {c["key"]: c for c in plan["cast"]}
        who = "; ".join("image %d is %s" % (i + 1, cast[k]["name"]) for i, k in enumerate(shot["cast"]))
        clothes = "; ".join("%s wears %s" % (cast[k]["name"], cast[k]["wardrobe"]) for k in shot["cast"])
        return FACE_LOCK.format(who=who, clothes=clothes) + world + FACE_GUARD + TEXT_GUARD + LAYOUT_GUARD
    return world + NO_PEOPLE + TEXT_GUARD + LAYOUT_GUARD


def motion_prompt(beat, shot):
    amp = "calm" if shot["has_text"] else "punchy"   # LESSON: busy motion garbled text and bent props
    text_lock = ("Keep every printed word sharp, legible and stable — do not warp or wobble the lettering. "
                 if shot["has_text"] else "")
    guard = ((FREEZE if shot["cast"] else "") + text_lock +
             "Keep the layout stable. Stay flat 2D — no 3D rotation, no perspective change, camera parallel "
             "to the poster. ONE continuous move that does not loop, retract or reset. Rigid paper — no "
             "morph/melt; straight posts and poles stay straight and upright. Animate the motion only; don't "
             "re-render the picture.")
    return ("Animate this still into a mixed-media paper-collage MOTION GRAPHIC, printed cut-outs, not "
            "photoreal.\nCAMERA (one move only): %s.\nELEMENT MOTION (%s): %s. Elements move as paper cut-outs "
            "(slide, flap, hinge, pop).\nAESTHETIC: keep the torn-paper, tape, halftone, newsprint and "
            "paper-stencil textures and the bold flat background.\nCOLOR: %s, high contrast.\nCONSTRAINTS: %s"
            % (CAMERA[shot["camera"]], AMPLITUDE[amp], shot["motion"], beat["bg"], guard))[:2500]


def kling_seconds(need):
    """Shortest Kling length that covers the shot (it returns duration + 0.04 s; min 3, max 15)."""
    return int(min(15, max(3, math.ceil(need + 0.05))))


def cmd_requests(job, kind, only, attempt):
    plan = job.plan()
    reqs = []

    def spec(k, sid, tool, model, inp, uploads=None, folder=kind):
        name = "%s_%s_%s_%d" % (job.id, k, sid, attempt) if sid else "%s_%s_%d" % (job.id, k, attempt)
        return {"key": ("%s-%s-%s-%d" % (job.id, k, sid, attempt)) if sid else "%s-%s-%d" % (job.id, k, attempt),
                "gen": "%s:%s" % (k, sid) if sid else k, "id": sid, "attempt": attempt, "tool": tool,
                "modelId": MODEL[model], "input": inp, "uploads": uploads or {}, "outputName": name,
                "folder": os.path.join(job.dir, "gen", folder)}

    if kind == "narration":
        lang = plan["lang"]
        for b in plan["beats"]:
            if not only or str(b["n"]) in only:
                reqs.append(spec("narr", str(b["n"]), "audio", "tts",
                                 {"text": b["narration"], "voice": VOICE, "language_code": lang, "stability": 0.5}))
    elif kind == "keyframes":
        for b, s in shots_of(plan):
            if only and s["id"] not in only:
                continue
            inp = {"prompt": keyframe_prompt(plan, b, s), "aspect_ratio": "9:16", "resolution": "2K",
                   "num_images": 1, "output_format": "png"}
            uploads = {}
            if s["cast"]:
                slots = ["p%d" % (i + 1) for i in range(len(s["cast"]))]
                inp["image_urls"] = ["selects-input:" + x for x in slots]
                uploads = {slot: os.path.join(job.dir, "portraits", "%s.jpg" % k) for slot, k in zip(slots, s["cast"])}
            reqs.append(spec("kf", s["id"], "image", "edit" if s["cast"] else "t2i", inp, uploads))
    elif kind == "clips":
        tl = load(os.path.join(job.dir, "timeline.json"))
        need = {x["shot"]: x for x in tl["segments"]}
        for b, s in shots_of(plan):
            if only and s["id"] not in only:
                continue
            kf = job.file("kf:" + s["id"])
            if not kf:
                raise EngineError("keyframe missing: " + s["id"])
            reqs.append(spec("clip", s["id"], "video", "i2v",
                             {"prompt": motion_prompt(b, s), "start_image_url": "selects-input:start",
                              "duration": str(need[s["id"]]["kling"]), "generate_audio": False},
                             {"start": kf}))
    elif kind == "music":
        tl = load(os.path.join(job.dir, "timeline.json"))
        reqs.append(spec("music", "", "audio", "music",
                         {"prompt": MUSIC_PROMPT, "force_instrumental": True, "music_length_ms": tl["music_ms"]}))
    else:
        raise EngineError("unknown request kind " + kind)
    out({"ok": True, "requests": reqs})


# ---- timeline: narration timing from the audio itself --------------------------------------------
def silences(path):
    r = subprocess.run([find_tool("ffmpeg"), "-hide_banner", "-nostats", "-i", path, "-af",
                        "silencedetect=noise=-38dB:d=0.12", "-f", "null", "-"], capture_output=True, text=True)
    starts = [float(x) for x in re.findall(r"silence_start: ([\d.]+)", r.stderr)]
    ends = [float(x) for x in re.findall(r"silence_end: ([\d.]+)", r.stderr)]
    return list(zip(starts, ends + [None] * (len(starts) - len(ends))))


def align_words(text, dur, sil, lang):
    """Word start times without provider timestamps. Speech between the leading and trailing silence is
    shared out by each word's speech weight, and every internal pause is placed at the word boundary
    nearest its position, preferring boundaries after punctuation. Returns [(word, start, end)]."""
    words = text.split()
    wts = [word_weight(w, lang) for w in words]
    sil = [(a, b if b is not None else dur) for a, b in sil]
    s0 = sil[0][1] if sil and sil[0][0] <= 0.05 else 0.0
    s1 = sil[-1][0] if sil and sil[-1][1] >= dur - 0.05 and sil[-1][0] > s0 else dur
    inner = [(a, b) for a, b in sil if a > s0 + 0.05 and b < s1 - 0.05]
    speech = max(0.1, (s1 - s0) - sum(b - a for a, b in inner))
    total = sum(wts)
    cum, acc = [], 0.0
    for w in wts:
        acc += w
        cum.append(acc)          # cumulative weight after word i
    pause_after = [0.0] * len(words)
    used, removed = set(), 0.0
    avg = total / max(1, len(words))
    for a, b in inner:
        pos = (a - s0 - removed) / speech * total
        best, score = None, None
        for j in range(len(words) - 1):
            if j in used:
                continue
            sc = abs(cum[j] - pos) - (0.8 * avg if re.search(r"[.,!?;:。、，！？]$", words[j]) else 0)
            if score is None or sc < score:
                best, score = j, sc
        if best is not None:
            used.add(best)
            pause_after[best] += b - a
        removed += b - a
    out_words, extra = [], 0.0
    for i, w in enumerate(words):
        start = s0 + (cum[i] - wts[i]) / total * speech + extra
        end = s0 + cum[i] / total * speech + extra
        out_words.append((w, round(start, 3), round(end, 3)))
        extra += pause_after[i]
    return out_words


def cmd_timeline(job):
    plan = job.plan()
    lang = plan["lang"]
    t, segs, narr, heads, cues = 0.0, [], [], [], []
    for b in plan["beats"]:
        path = job.file("narr:%d" % b["n"])
        if not path:
            raise EngineError("narration missing: beat %d" % b["n"])
        nd = media_duration(path)
        ws = align_words(b["narration"], nd, silences(path), lang)
        last = b["n"] == len(plan["beats"])
        length = LEAD + nd + TAIL + (END_HOLD if last else 0)
        cuts = [0.0]
        if len(b["shots"]) == 2 and b.get("cut_index") and b["cut_index"] < len(ws):
            cuts.append(round(LEAD + ws[b["cut_index"]][1] - 0.05, 3))
        cuts.append(round(length, 3))
        if len(cuts) == 3 and (cuts[1] < 1.5 or length - cuts[1] < 1.5):
            cuts = [0.0, cuts[2]]
            b["shots"] = b["shots"][:1]
        for i, s in enumerate(b["shots"]):
            need = cuts[i + 1] - cuts[i]
            segs.append({"shot": s["id"], "start": round(t + cuts[i], 3), "need": round(need, 3), "kling": kling_seconds(need)})
        narr.append({"beat": b["n"], "file": path, "start": round(t + LEAD, 3), "dur": round(nd, 3)})
        heads.append({"beat": b["n"], "text": b["title"], "start": round(t, 3), "end": round(t + length, 3)})
        lines = b["captions"]
        if sum(len(l.split()) for l in lines) != len(ws):
            lines = auto_captions(" ".join(w[0] for w in ws), LANG[lang]["cap"])
        idx, starts = 0, []
        for line in lines:
            starts.append(ws[min(idx, len(ws) - 1)][1])
            idx += len(line.split())
        for i, line in enumerate(lines):
            a = t + LEAD + starts[i]
            e = t + LEAD + (starts[i + 1] if i + 1 < len(lines) else nd + 0.15)
            cues.append({"text": line.rstrip(",.、，"), "start": round(a, 3), "end": round(e, 3)})
        t += length
    save(job.p("plan.json"), plan)
    # LESSON: music bills by started minute; 60.03 s cost two. Stay under the boundary.
    need_s = t + 2
    music_s = min(math.ceil(need_s), 60 * math.ceil(need_s / 60.0) - 1)
    save(job.p("timeline.json"), {"total": round(t, 3), "segments": segs, "narration": narr, "headlines": heads,
                                  "captions": cues, "music_ms": int(music_s * 1000)})
    job.data["stage"] = "timed"
    job.save()
    out({"ok": True, "seconds": round(t, 3), "shots": len(segs), "videoSeconds": sum(s["kling"] for s in segs)})


# ---- sheet, Ken Burns, assembly ---------------------------------------------------------------------
def cmd_sheet(job, only=None):
    plan = job.plan()
    ff = find_tool("ffmpeg")
    ids = [s["id"] for _, s in shots_of(plan) if not only or s["id"] in only]
    font = "/System/Library/Fonts/Supplemental/Arial.ttf"
    sheets = []
    for part in range(0, len(ids), 12):
        chunk = ids[part:part + 12]
        cols = 4 if len(chunk) > 6 else max(1, min(3, len(chunk)))
        args, filt = [], ""
        for i, sid in enumerate(chunk):
            args += ["-i", job.file("kf:" + sid)]
            label = ("drawtext=fontfile=%s:text='%s':x=8:y=8:fontsize=34:fontcolor=white:box=1:boxcolor=black@0.8:boxborderw=6,"
                     % (font, sid)) if os.path.exists(font) else ""
            filt += "[%d:v]scale=270:480,%spad=276:486:3:3:white[v%d];" % (i, label, i)
        layout = "|".join("%d_%d" % ((i % cols) * 276, (i // cols) * 486) for i in range(len(chunk)))
        stack = "".join("[v%d]" % i for i in range(len(chunk))) + (
            "xstack=inputs=%d:layout=%s:fill=white" % (len(chunk), layout) if len(chunk) > 1 else "null")
        dest = job.p("check", "sheet_%d_%d.jpg" % (int(time.time()), part // 12 + 1))
        r = subprocess.run([ff, "-loglevel", "error", "-y"] + args + ["-filter_complex", filt + stack, "-frames:v", "1",
                                                                       "-q:v", "4", dest], capture_output=True, text=True)
        if r.returncode != 0:
            raise EngineError("sheet: " + r.stderr[-300:])
        sheets.append({"path": dest, "shots": chunk})
    cast = {c["key"]: c["name"] for c in plan["cast"]}
    expect = [{"shot": s["id"], "people": [cast[k] for k in s["cast"]],
               "words": re.findall(r"['\"“‘]([^'\"”’]{1,40})['\"”’]", s["scene"]), "scene": s["scene"][:300]}
              for _, s in shots_of(plan) if not only or s["id"] in only]
    out({"ok": True, "sheets": sheets, "expect": expect})


def ken_burns(img, dest, dur, zoom_in=True):
    frames = int(math.ceil(dur * FPS))
    z = "min(zoom+0.0009,1.18)" if zoom_in else "if(eq(on,1),1.18,max(zoom-0.0009,1.0))"
    vf = ("[0:v]scale=%d:%d:force_original_aspect_ratio=increase,crop=%d:%d,boxblur=26:2[bg];"
          "[0:v]scale=%d:%d:force_original_aspect_ratio=decrease[fg];"
          "[bg][fg]overlay=(W-w)/2:(H-h)/2,setsar=1,scale=%d:%d,"
          "zoompan=z='%s':d=%d:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s=%dx%d:fps=%d[v]"
          % (W, H, W, H, W, H, W * 2, H * 2, z, frames, W, H, FPS))
    r = subprocess.run([find_tool("ffmpeg"), "-y", "-loglevel", "error", "-loop", "1", "-i", img, "-filter_complex", vf,
                        "-map", "[v]", "-t", "%.3f" % dur, "-c:v", "libx264", "-pix_fmt", "yuv420p", dest],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise EngineError("ken burns: " + r.stderr[-300:])


def cmd_kenburns(job, only):
    plan = job.plan()
    tl = load(os.path.join(job.dir, "timeline.json"))
    need = {x["shot"]: x for x in tl["segments"]}
    order = [s["id"] for _, s in shots_of(plan)]
    made = {}
    for sid in only or []:
        dest = job.p("gen", "kenburns", "%s_kb_%s.mp4" % (job.id, sid))
        ken_burns(job.file("kf:" + sid), dest, need[sid]["need"] + 0.3, zoom_in=order.index(sid) % 2 == 0)
        made[sid] = dest
    out({"ok": True, "clips": made})


def headline_size(text):
    units = sum(1.0 if re.match(r"[぀-ヿ\u3131-\ud7a3一-鿿]", ch) else 0.3 if ch == " " else 0.62 for ch in text)
    return int(min(100, 860 / max(units, 1)))


def credit_line(portraits, lang):
    groups = {}
    for p in portraits.values():
        if p.get("ok"):
            lic = LANG[lang]["pd"] if re.search(r"public domain|^pd|cc0", p["license"], re.I) else p["license"]
            groups.setdefault(lic, set()).add(p.get("artist") or "")
    if not groups:
        return ""
    parts = ["%s(%s)" % (", ".join(sorted(a for a in v if a)), lic) if any(v) else lic for lic, v in groups.items()]
    return "%s · Wikimedia Commons: %s" % (LANG[lang]["photos"], "; ".join(parts))


def cmd_assembly(job):
    plan = job.plan()
    lang = plan["lang"]
    tl = load(os.path.join(job.dir, "timeline.json"))
    art = load(os.path.join(job.dir, "article.json"), {})
    segs = []
    for s in tl["segments"]:
        f = job.file("clip:" + s["shot"])
        if not f:
            raise EngineError("clip missing: %s" % s["shot"])
        segs.append({"shot": s["shot"], "file": f, "dur": round(min(s["need"], media_duration(f) - 0.02), 3)})
    music = job.file("music") or ""
    source = plan.get("source_line") or ""
    if not source and art.get("url"):
        date = (art.get("date") or "")[:10].replace("-", ".")
        source = "%s · %s" % (LANG[lang]["source"], " ".join(x for x in (art.get("source"), date, art.get("byline")) if x))
    files = [s["file"] for s in segs] + [n["file"] for n in tl["narration"]] + ([music] if music else [])
    res = {"draftName": "%s · Vox" % (plan.get("title") or art.get("title") or "Explainer")[:60], "files": files,
           "segments": segs, "narration": tl["narration"], "music": music,
           "headlines": [dict(h, size=headline_size(h["text"])) for h in tl["headlines"]],
           "captions": tl["captions"],
           "credit": {"start": round(tl["total"] - END_HOLD + 0.2, 3), "source": source,
                      "photos": credit_line(job.data.get("portraits", {}), lang)}}
    save(job.p("selects.json"), res)
    job.data["stage"] = "assembled"
    job.save()
    out(res)


def cmd_check():
    info = {"version": VERSION, "python": sys.version.split()[0], "ffmpeg": find_tool("ffmpeg"), "ffprobe": find_tool("ffprobe")}
    info["ok"] = bool(info["ffmpeg"] and info["ffprobe"])
    out(info)


def main(argv):
    if len(argv) < 2:
        raise EngineError("usage: engine.py <command> [job]")
    cmd = argv[1]
    if cmd == "check":
        return cmd_check()
    job = Job(argv[2])
    rest = argv[3:]
    attempt = int(rest[rest.index("--attempt") + 1]) if "--attempt" in rest else 1
    pos = [x for i, x in enumerate(rest) if not x.startswith("--") and (i == 0 or rest[i - 1] != "--attempt")]
    if cmd == "requests":
        only = set(pos[1].split(",")) if len(pos) > 1 and pos[1] else None
        return cmd_requests(job, pos[0], only, attempt)
    only = set(pos[0].split(",")) if pos and pos[0] else None
    handlers = {"fetch": lambda: cmd_fetch(job), "validate": lambda: cmd_validate(job),
                "portraits": lambda: cmd_portraits(job), "timeline": lambda: cmd_timeline(job),
                "sheet": lambda: cmd_sheet(job, only), "kenburns": lambda: cmd_kenburns(job, sorted(only or [])),
                "assembly": lambda: cmd_assembly(job)}
    if cmd not in handlers:
        raise EngineError("unknown command " + cmd)
    return handlers[cmd]()


if __name__ == "__main__":
    try:
        main(sys.argv)
    except EngineError as e:
        out({"ok": False, "error": str(e)})
        sys.exit(2)
    except Exception as e:  # noqa: BLE001 — the panel shows the message
        out({"ok": False, "error": "%s: %s" % (type(e).__name__, e)})
        sys.exit(3)
