// @name Vox Style Explainer
// @name:de Erklärvideo im Vox-Stil
// @name:en Vox Style Explainer
// @name:es Vídeo explicativo estilo Vox
// @name:fr Vidéo explicative style Vox
// @name:it Video esplicativo stile Vox
// @name:ja Vox風の解説動画
// @name:ko Vox Style Explainer
// @name:pt Vídeo explicativo estilo Vox
// @name:tr Vox tarzı açıklama videosu
// @name:zh Vox 风格解说视频
// @icon video
// Turns a link or pasted text into a Vox-style paper-collage explainer Draft in the current Project:
// 9:16, narration in the source's language, real people as Wikimedia Commons photo cut-outs, and an
// editable headline, captions and source credit. Images, motion, voice and music are generated by
// Selects (the user's Selects credits); the bundled engine does the local work.
import React from "react";

const APP_ID = "vox-explainer";
// The engine is installed with the plugin at SELECTS_USER_SKILLS_ROOT/vox-explainer/engine.py
const ENGINE = '"$SELECTS_USER_SKILLS_ROOT/vox-explainer/engine.py"';
const IS_WIN = typeof navigator !== "undefined" && /Windows/i.test(navigator.userAgent || "");
const TPL: Record<string, string> = { headline: "import React from 'react';\nimport { useCurrentFrame, useVideoConfig, interpolate, spring } from 'remotion';\n\nconst FALLBACK = \"'Apple SD Gothic Neo','Pretendard','Noto Sans KR',sans-serif\";\n\n// Constructivist headline: a slanted black bar with cream type and a red offset block.\nexport default function Headline({ data }) {\n  const frame = useCurrentFrame();\n  const { fps, width } = useVideoConfig();\n  const k = width / 1080;\n  const text = String(data?.text ?? '');\n  const size = Number(data?.fontSize ?? 92);\n  const top = Number(data?.top ?? 110);\n  const bar = String(data?.barColor ?? '#141414');\n  const fg = String(data?.textColor ?? '#F4ECDD');\n  const accent = String(data?.accentColor ?? '#D7261E');\n  const family = typeof data?.fontFamily === 'string' ? data.fontFamily.trim() : '';\n  const fontFamily = family === '' ? FALLBACK : `\"${family}\", ${FALLBACK}`;\n  const p = spring({ frame, fps, config: { damping: 16, stiffness: 170 } });\n  const x = interpolate(p, [0, 1], [-1200, 0]);\n  const ax = interpolate(p, [0, 1], [900, 0]);\n  return (\n    <div style={{ position: 'absolute', left: 0, top: top * k, width: '100%', height: 320 * k, pointerEvents: 'none' }}>\n      <div style={{ position: 'absolute', left: 70 * k, top: 8 * k, width: 300 * k, height: 34 * k, background: accent, transform: `translateX(${ax * k}px) rotate(-7deg)` }} />\n      <div style={{ position: 'absolute', left: 24 * k, right: 24 * k, top: 58 * k, display: 'flex', justifyContent: 'center', transform: `translateX(${x * k}px) rotate(-4deg)` }}>\n        <div style={{ background: bar, color: fg, fontFamily, fontWeight: 900, fontSize: size * k, letterSpacing: `${-2 * k}px`, lineHeight: 1.12, padding: `${16 * k}px ${34 * k}px ${22 * k}px`, boxShadow: `${12 * k}px ${12 * k}px 0 ${accent}`, whiteSpace: 'nowrap' }}>{text}</div>\n      </div>\n    </div>\n  );\n}\n", caption: "import React from 'react';\nimport { useVideoConfig } from 'remotion';\n\nconst FALLBACK = \"'Apple SD Gothic Neo','Pretendard','Noto Sans KR',sans-serif\";\n\n// Spoken-line caption: cream type on a black box, low third of a 9:16 frame.\nexport default function Caption({ data }) {\n  const { width } = useVideoConfig();\n  const k = width / 1080;\n  const lines = String(data?.text ?? '').split('\\n');\n  const size = Number(data?.fontSize ?? 56);\n  const bottom = Number(data?.bottom ?? 1560);\n  const family = typeof data?.fontFamily === 'string' ? data.fontFamily.trim() : '';\n  const fontFamily = family === '' ? FALLBACK : `\"${family}\", ${FALLBACK}`;\n  return (\n    <div style={{ position: 'absolute', left: 40 * k, width: 1000 * k, top: 0, height: bottom * k, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-end', pointerEvents: 'none' }}>\n      <div style={{ background: String(data?.boxColor ?? 'rgba(20,20,20,0.86)'), padding: `${10 * k}px ${26 * k}px ${14 * k}px`, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>\n        {lines.map((line, i) => (\n          <div key={i} style={{ fontFamily, fontSize: size * k, fontWeight: 700, color: String(data?.textColor ?? '#F4ECDD'), lineHeight: 1.3, letterSpacing: `${-1 * k}px`, whiteSpace: 'nowrap' }}>{line}</div>\n        ))}\n      </div>\n    </div>\n  );\n}\n", credit: "import React from 'react';\nimport { useCurrentFrame, useVideoConfig, interpolate } from 'remotion';\n\nconst FALLBACK = \"'Apple SD Gothic Neo','Pretendard','Noto Sans KR',sans-serif\";\n\n// Closing source and photo credit strip.\nexport default function Credit({ data }) {\n  const frame = useCurrentFrame();\n  const { width } = useVideoConfig();\n  const k = width / 1080;\n  const o = interpolate(frame, [0, 8], [0, 1], { extrapolateRight: 'clamp' });\n  const family = typeof data?.fontFamily === 'string' ? data.fontFamily.trim() : '';\n  const fontFamily = family === '' ? FALLBACK : `\"${family}\", ${FALLBACK}`;\n  return (\n    <div style={{ position: 'absolute', left: 50 * k, right: 50 * k, top: Number(data?.top ?? 1600) * k, opacity: o, pointerEvents: 'none', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>\n      <div style={{ background: '#F4ECDD', color: '#141414', fontFamily, padding: `${14 * k}px ${24 * k}px`, borderLeft: `${10 * k}px solid #D7261E`, display: 'flex', flexDirection: 'column', gap: 6 * k }}>\n        <div style={{ fontSize: Number(data?.sourceSize ?? 34) * k, fontWeight: 800 }}>{String(data?.source ?? '')}</div>\n        <div style={{ fontSize: Number(data?.photoSize ?? 21) * k, fontWeight: 500, lineHeight: 1.3 }}>{String(data?.photos ?? '')}</div>\n      </div>\n    </div>\n  );\n}\n" };
const CAPTION_BOTTOM = 1790;
const MUSIC_DB = -19;

type Strings = {
  sourceTitle: string; link: string; text: string; url: string; body: string; bodyPh: string; target: string;
  makePlan: string; planning: string; planTitle: string; redo: string;
  summary: (s: number, b: number, sh: number, lang: string) => string; people: string; warnings: string;
  produce: string; producing: string; steps: string[]; done: string; openHint: string; fallback: string;
  missing: string; rerolled: (n: number) => string; checkOk: string; unverified: string; noProject: string;
  needUrl: string; needText: string; noPython: string; noGeneration: string; recent: string; resume: string;
  dismiss: string; retry: string; elapsed: string; noMusic: string; macOnly: string; noEngine: string;
  errors: Record<string, string>;
};

const STRINGS: Record<string, Strings> = {
  en: {
    sourceTitle: "Source", link: "Link", text: "Text", url: "Source link", body: "Source text",
    bodyPh: "Paste the title and body", target: "Target length", makePlan: "Draft the script",
    planning: "Drafting…", planTitle: "Script", redo: "Redo the script",
    summary: (s, b, sh, l) => `About ${s}s · ${b} beats · ${sh} shots · ${l}`, people: "People",
    warnings: "Auto-fixed", produce: "Make the video", producing: "Making…",
    steps: ["Read source", "Script", "Portraits & voice", "Keyframes", "Image check", "Motion", "Draft"],
    done: "The Draft is ready", openHint: "Open it from the Project's Draft list. Export with Handoff → Export.",
    fallback: "Shots that use a zoom instead of motion",
    missing: "People shown as silhouettes (no free-licence photo)",
    rerolled: (n) => `The image check remade ${n} shot(s).`, checkOk: "Image check: no problems",
    unverified: "Shots the check still noted after remaking (worth a look)",
    noProject: "Open a Project first.", needUrl: "Enter a source link.",
    needText: "Paste at least 80 characters of source text.",
    noPython: "Python 3.9 or later was not found. Run xcode-select --install in Terminal, then try again.",
    noGeneration: "This Selects version cannot generate media from apps. Update Selects.",
    recent: "Unfinished jobs", resume: "Resume", dismiss: "Remove from list", retry: "Try again", elapsed: "Elapsed",
    noMusic: "The music could not be made; the Draft has no music.",
    macOnly: "This app works on macOS for now.", noEngine: "The app's files are incomplete. Reinstall it from the Plugin Library.",
    errors: { FETCH_FAILED: "The link could not be opened.", NO_TEXT: "No text was found at the link. Paste the text instead.",
      TEXT_TOO_SHORT: "The source text is too short.", NO_JSON: "The script could not be read from the AI answer. Try again." },
  },
  ko: {
    sourceTitle: "\uc6d0\ubb38", link: "\ub9c1\ud06c", text: "\ud14d\uc2a4\ud2b8", url: "\uc6d0\ubb38 \ub9c1\ud06c", body: "\uc6d0\ubb38 \ud14d\uc2a4\ud2b8",
    bodyPh: "\uc81c\ubaa9\uacfc \ubcf8\ubb38\uc744 \ubd99\uc5ec\ub123\uc73c\uc138\uc694", target: "\ubaa9\ud45c \uae38\uc774", makePlan: "\uad6c\uc131\uc548 \ub9cc\ub4e4\uae30",
    planning: "\uad6c\uc131\uc548 \ub9cc\ub4dc\ub294 \uc911…", planTitle: "\uad6c\uc131\uc548", redo: "\uad6c\uc131\uc548 \ub2e4\uc2dc \ub9cc\ub4e4\uae30",
    summary: (s, b, sh, l) => `\uc57d ${s}\ucd08 · \uc7a5\uba74 ${b} · \uc0f7 ${sh} · ${l}`, people: "\uc778\ubb3c",
    warnings: "\uc790\ub3d9 \uc218\uc815", produce: "\uc601\uc0c1 \ub9cc\ub4e4\uae30", producing: "\ub9cc\ub4dc\ub294 \uc911…",
    steps: ["\uc6d0\ubb38 \uc77d\uae30", "\uad6c\uc131\uc548", "\uc778\ubb3c \uc0ac\uc9c4·\ub0b4\ub808\uc774\uc158", "\ud0a4\ud504\ub808\uc784", "\uc774\ubbf8\uc9c0 \uc810\uac80", "\uc6c0\uc9c1\uc784", "\ub4dc\ub798\ud504\ud2b8"],
    done: "\ub4dc\ub798\ud504\ud2b8\ub97c \ub9cc\ub4e4\uc5c8\uc2b5\ub2c8\ub2e4", openHint: "\ud504\ub85c\uc81d\ud2b8\uc758 \ub4dc\ub798\ud504\ud2b8 \ubaa9\ub85d\uc5d0\uc11c \uc5f4 \uc218 \uc788\uc2b5\ub2c8\ub2e4. \ub0b4\ubcf4\ub0b4\uae30\ub294 Handoff → Export\ub97c \uc4f0\uc138\uc694.",
    fallback: "\uc6c0\uc9c1\uc784 \ub300\uc2e0 \ud655\ub300 \ud6a8\uacfc\ub97c \uc4f4 \uc0f7", missing: "\uc790\uc720 \ub77c\uc774\uc120\uc2a4 \uc0ac\uc9c4\uc774 \uc5c6\uc5b4 \uc2e4\ub8e8\uc5e3\uc73c\ub85c \ubc14\uafbc \uc778\ubb3c",
    rerolled: (n) => `\uc774\ubbf8\uc9c0 \uc810\uac80\uc5d0\uc11c ${n}\uac1c \uc0f7\uc744 \ub2e4\uc2dc \ub9cc\ub4e4\uc5c8\uc2b5\ub2c8\ub2e4.`, checkOk: "\uc774\ubbf8\uc9c0 \uc810\uac80: \ubb38\uc81c \uc5c6\uc74c",
    unverified: "\ub2e4\uc2dc \ub9cc\ub4e0 \ub4a4\uc5d0\ub3c4 \uc810\uac80\uc5d0\uc11c \uc9c0\uc801\ub41c \uc0f7(\ud655\uc778 \uad8c\uc7a5)",
    noProject: "\ud504\ub85c\uc81d\ud2b8\ub97c \uba3c\uc800 \uc5ec\uc138\uc694.", needUrl: "\uc6d0\ubb38 \ub9c1\ud06c\ub97c \ub123\uc73c\uc138\uc694.", needText: "\uc6d0\ubb38 \ud14d\uc2a4\ud2b8\ub97c 80\uc790 \uc774\uc0c1 \ub123\uc73c\uc138\uc694.",
    noPython: "Python 3.9 \uc774\uc0c1\uc744 \ucc3e\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4. \ud130\ubbf8\ub110\uc5d0\uc11c xcode-select --install \uc744 \uc2e4\ud589\ud55c \ub4a4 \ub2e4\uc2dc \uc2dc\ub3c4\ud558\uc138\uc694.",
    noGeneration: "\uc774 Selects \ubc84\uc804\uc740 \uc571\uc5d0\uc11c \ubbf8\ub514\uc5b4 \uc0dd\uc131\uc744 \uc9c0\uc6d0\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. Selects\ub97c \uc5c5\ub370\uc774\ud2b8\ud558\uc138\uc694.",
    recent: "\uc9c4\ud589 \uc911\uc778 \uc791\uc5c5", resume: "\uc774\uc5b4\uc11c \ub9cc\ub4e4\uae30", dismiss: "\ubaa9\ub85d\uc5d0\uc11c \uc9c0\uc6b0\uae30", retry: "\ub2e4\uc2dc \uc2dc\ub3c4", elapsed: "\uacbd\uacfc",
    noMusic: "\ubc30\uacbd\uc74c\uc545\uc744 \ub9cc\ub4e4\uc9c0 \ubabb\ud574 \uc74c\uc545 \uc5c6\uc774 \ub9cc\ub4e4\uc5c8\uc2b5\ub2c8\ub2e4.",
    macOnly: "\uc774 \uc571\uc740 \uc9c0\uae08\uc740 macOS\uc5d0\uc11c\ub9cc \ub3d9\uc791\ud569\ub2c8\ub2e4.", noEngine: "\uc571 \ud30c\uc77c\uc774 \ube60\uc838 \uc788\uc2b5\ub2c8\ub2e4. \ud50c\ub7ec\uadf8\uc778 \ub77c\uc774\ube0c\ub7ec\ub9ac\uc5d0\uc11c \ub2e4\uc2dc \uc124\uce58\ud558\uc138\uc694.",
    errors: { FETCH_FAILED: "\ub9c1\ud06c\ub97c \uc5f4\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4.", NO_TEXT: "\ub9c1\ud06c\uc5d0\uc11c \ubcf8\ubb38\uc744 \ucc3e\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4. \ud14d\uc2a4\ud2b8\ub85c \ubd99\uc5ec\ub123\uc5b4 \uc8fc\uc138\uc694.",
      TEXT_TOO_SHORT: "\uc6d0\ubb38 \ud14d\uc2a4\ud2b8\uac00 \ub108\ubb34 \uc9e7\uc2b5\ub2c8\ub2e4.", NO_JSON: "AI \uc751\ub2f5\uc5d0\uc11c \uad6c\uc131\uc548\uc744 \uc77d\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4. \ub2e4\uc2dc \uc2dc\ub3c4\ud558\uc138\uc694." },
  },
  ja: {
    sourceTitle: "原文", link: "リンク", text: "テキスト", url: "原文のリンク", body: "原文テキスト",
    bodyPh: "タイトルと本文を貼り付けてください", target: "目標の長さ", makePlan: "構成案を作成",
    planning: "構成案を作成中…", planTitle: "構成案", redo: "構成案を作り直す",
    summary: (s, b, sh, l) => `約${s}秒 · ${b}場面 · ${sh}ショット · ${l}`, people: "人物",
    warnings: "自動修正", produce: "動画を作成", producing: "作成中…",
    steps: ["原文を読む", "構成案", "人物写真・ナレーション", "キーフレーム", "画像チェック", "モーション", "ドラフト"],
    done: "ドラフトを作成しました", openHint: "プロジェクトのドラフト一覧から開けます。書き出しは Handoff → Export を使ってください。",
    fallback: "モーションの代わりにズームを使ったショット", missing: "自由ライセンスの写真がなくシルエットにした人物",
    rerolled: (n) => `画像チェックで${n}ショットを作り直しました。`, checkOk: "画像チェック: 問題なし",
    unverified: "作り直した後もチェックで指摘されたショット(確認をおすすめします)",
    noProject: "先にプロジェクトを開いてください。", needUrl: "原文のリンクを入力してください。",
    needText: "原文テキストを80文字以上貼り付けてください。",
    noPython: "Python 3.9以降が見つかりません。ターミナルで xcode-select --install を実行してから再試行してください。",
    noGeneration: "このバージョンのSelectsはアプリからのメディア生成に対応していません。Selectsを更新してください。",
    recent: "未完了のジョブ", resume: "続きから作成", dismiss: "一覧から削除", retry: "再試行", elapsed: "経過",
    noMusic: "BGMを作成できなかったため、音楽なしで作成しました。",
    macOnly: "このアプリは現在 macOS でのみ動作します。", noEngine: "アプリのファイルが不足しています。プラグインライブラリから再インストールしてください。",
    errors: { FETCH_FAILED: "リンクを開けませんでした。", NO_TEXT: "リンクから本文が見つかりませんでした。テキストで貼り付けてください。",
      TEXT_TOO_SHORT: "原文テキストが短すぎます。", NO_JSON: "AIの回答から構成案を読み取れませんでした。再試行してください。" },
  },
  zh: {
    sourceTitle: "原文", link: "链接", text: "文本", url: "原文链接", body: "原文文本",
    bodyPh: "粘贴标题和正文", target: "目标时长", makePlan: "生成脚本",
    planning: "正在生成脚本…", planTitle: "脚本", redo: "重新生成脚本",
    summary: (s, b, sh, l) => `约${s}秒 · ${b}个场景 · ${sh}个镜头 · ${l}`, people: "人物",
    warnings: "已自动修正", produce: "生成视频", producing: "正在生成…",
    steps: ["读取原文", "脚本", "人物照片与旁白", "关键帧", "图像检查", "动态", "草稿"],
    done: "草稿已创建", openHint: "可在项目的草稿列表中打开。导出请使用 Handoff → Export。",
    fallback: "以缩放代替动态的镜头", missing: "因无自由许可照片而改为剪影的人物",
    rerolled: (n) => `图像检查后重新生成了${n}个镜头。`, checkOk: "图像检查：没有问题",
    unverified: "重新生成后检查仍有提示的镜头（建议确认）",
    noProject: "请先打开项目。", needUrl: "请输入原文链接。", needText: "请粘贴至少80个字符的原文文本。",
    noPython: "未找到 Python 3.9 或更高版本。请在终端运行 xcode-select --install 后重试。",
    noGeneration: "此版本的 Selects 不支持在应用中生成媒体。请更新 Selects。",
    recent: "未完成的任务", resume: "继续生成", dismiss: "从列表中移除", retry: "重试", elapsed: "已用时",
    noMusic: "未能生成背景音乐，草稿中没有音乐。",
    macOnly: "此应用目前仅支持 macOS。", noEngine: "应用文件不完整。请从插件库重新安装。",
    errors: { FETCH_FAILED: "无法打开链接。", NO_TEXT: "未能从链接中找到正文，请粘贴文本。",
      TEXT_TOO_SHORT: "原文文本太短。", NO_JSON: "无法从 AI 回复中读取脚本，请重试。" },
  },
  de: {
    sourceTitle: "Quelle", link: "Link", text: "Text", url: "Link zur Quelle", body: "Quelltext",
    bodyPh: "Titel und Text einfügen", target: "Ziellänge", makePlan: "Skript erstellen",
    planning: "Skript wird erstellt…", planTitle: "Skript", redo: "Skript neu erstellen",
    summary: (s, b, sh, l) => `Etwa ${s} s · ${b} Szenen · ${sh} Einstellungen · ${l}`, people: "Personen",
    warnings: "Automatisch korrigiert", produce: "Video erstellen", producing: "Wird erstellt…",
    steps: ["Quelle lesen", "Skript", "Porträts & Sprecher", "Keyframes", "Bildprüfung", "Bewegung", "Entwurf"],
    done: "Der Entwurf ist fertig", openHint: "Öffne ihn in der Entwurfsliste des Projekts. Exportieren mit Handoff → Export.",
    fallback: "Einstellungen mit Zoom statt Bewegung", missing: "Als Silhouette gezeigte Personen (kein frei lizenziertes Foto)",
    rerolled: (n) => `Die Bildprüfung hat ${n} Einstellung(en) neu erstellt.`, checkOk: "Bildprüfung: keine Probleme",
    unverified: "Einstellungen, zu denen die Prüfung nach der Neuerstellung noch etwas anmerkt (bitte ansehen)",
    noProject: "Öffne zuerst ein Projekt.", needUrl: "Gib einen Link zur Quelle ein.",
    needText: "Füge mindestens 80 Zeichen Quelltext ein.",
    noPython: "Python 3.9 oder neuer wurde nicht gefunden. Führe im Terminal xcode-select --install aus und versuche es erneut.",
    noGeneration: "Diese Selects-Version kann in Apps keine Medien erzeugen. Aktualisiere Selects.",
    recent: "Unfertige Aufträge", resume: "Fortsetzen", dismiss: "Aus der Liste entfernen", retry: "Erneut versuchen", elapsed: "Vergangen",
    noMusic: "Die Musik konnte nicht erstellt werden; der Entwurf hat keine Musik.",
    macOnly: "Diese App läuft derzeit nur unter macOS.", noEngine: "Die Dateien der App sind unvollständig. Installiere sie erneut aus der Plugin-Bibliothek.",
    errors: { FETCH_FAILED: "Der Link konnte nicht geöffnet werden.", NO_TEXT: "Unter dem Link wurde kein Text gefunden. Füge den Text ein.",
      TEXT_TOO_SHORT: "Der Quelltext ist zu kurz.", NO_JSON: "Das Skript konnte nicht aus der KI-Antwort gelesen werden. Versuche es erneut." },
  },
  es: {
    sourceTitle: "Fuente", link: "Enlace", text: "Texto", url: "Enlace a la fuente", body: "Texto de la fuente",
    bodyPh: "Pega el título y el cuerpo", target: "Duración objetivo", makePlan: "Crear guion",
    planning: "Creando guion…", planTitle: "Guion", redo: "Rehacer guion",
    summary: (s, b, sh, l) => `Unos ${s} s · ${b} escenas · ${sh} planos · ${l}`, people: "Personas",
    warnings: "Corregido automáticamente", produce: "Crear el vídeo", producing: "Creando…",
    steps: ["Leer la fuente", "Guion", "Retratos y voz", "Fotogramas clave", "Revisión de imágenes", "Movimiento", "Borrador"],
    done: "El borrador está listo", openHint: "Ábrelo desde la lista de borradores del proyecto. Exporta con Handoff → Export.",
    fallback: "Planos con zoom en lugar de movimiento", missing: "Personas mostradas como silueta (sin foto con licencia libre)",
    rerolled: (n) => `La revisión de imágenes rehízo ${n} plano(s).`, checkOk: "Revisión de imágenes: sin problemas",
    unverified: "Planos que la revisión aún señala tras rehacerlos (conviene revisarlos)",
    noProject: "Abre primero un proyecto.", needUrl: "Introduce un enlace a la fuente.",
    needText: "Pega al menos 80 caracteres del texto de la fuente.",
    noPython: "No se encontró Python 3.9 o posterior. Ejecuta xcode-select --install en Terminal y vuelve a intentarlo.",
    noGeneration: "Esta versión de Selects no puede generar contenido desde apps. Actualiza Selects.",
    recent: "Trabajos sin terminar", resume: "Continuar", dismiss: "Quitar de la lista", retry: "Reintentar", elapsed: "Transcurrido",
    noMusic: "No se pudo crear la música; el borrador no tiene música.",
    macOnly: "Por ahora esta app solo funciona en macOS.", noEngine: "Faltan archivos de la app. Vuelve a instalarla desde la biblioteca de plugins.",
    errors: { FETCH_FAILED: "No se pudo abrir el enlace.", NO_TEXT: "No se encontró texto en el enlace. Pega el texto.",
      TEXT_TOO_SHORT: "El texto de la fuente es demasiado corto.", NO_JSON: "No se pudo leer el guion en la respuesta de la IA. Vuelve a intentarlo." },
  },
  fr: {
    sourceTitle: "Source", link: "Lien", text: "Texte", url: "Lien de la source", body: "Texte de la source",
    bodyPh: "Collez le titre et le texte", target: "Durée cible", makePlan: "Créer le script",
    planning: "Création du script…", planTitle: "Script", redo: "Refaire le script",
    summary: (s, b, sh, l) => `Environ ${s} s · ${b} scènes · ${sh} plans · ${l}`, people: "Personnes",
    warnings: "Corrigé automatiquement", produce: "Créer la vidéo", producing: "Création…",
    steps: ["Lire la source", "Script", "Portraits et voix", "Images clés", "Vérification des images", "Mouvement", "Brouillon"],
    done: "Le brouillon est prêt", openHint: "Ouvrez-le depuis la liste des brouillons du projet. Exportez avec Handoff → Export.",
    fallback: "Plans avec un zoom au lieu du mouvement", missing: "Personnes montrées en silhouette (pas de photo sous licence libre)",
    rerolled: (n) => `La vérification a refait ${n} plan(s).`, checkOk: "Vérification des images : aucun problème",
    unverified: "Plans encore signalés après leur reprise (à regarder)",
    noProject: "Ouvrez d'abord un projet.", needUrl: "Saisissez un lien vers la source.",
    needText: "Collez au moins 80 caractères du texte source.",
    noPython: "Python 3.9 ou plus récent est introuvable. Lancez xcode-select --install dans le Terminal, puis réessayez.",
    noGeneration: "Cette version de Selects ne peut pas générer de médias depuis les apps. Mettez Selects à jour.",
    recent: "Tâches inachevées", resume: "Reprendre", dismiss: "Retirer de la liste", retry: "Réessayer", elapsed: "Écoulé",
    noMusic: "La musique n'a pas pu être créée ; le brouillon n'a pas de musique.",
    macOnly: "Cette app ne fonctionne pour l'instant que sur macOS.", noEngine: "Des fichiers de l'app manquent. Réinstallez-la depuis la bibliothèque de plugins.",
    errors: { FETCH_FAILED: "Impossible d'ouvrir le lien.", NO_TEXT: "Aucun texte trouvé à ce lien. Collez le texte.",
      TEXT_TOO_SHORT: "Le texte source est trop court.", NO_JSON: "Impossible de lire le script dans la réponse de l'IA. Réessayez." },
  },
  it: {
    sourceTitle: "Fonte", link: "Link", text: "Testo", url: "Link della fonte", body: "Testo della fonte",
    bodyPh: "Incolla titolo e testo", target: "Durata obiettivo", makePlan: "Crea copione",
    planning: "Creazione del copione…", planTitle: "Copione", redo: "Rifai il copione",
    summary: (s, b, sh, l) => `Circa ${s} s · ${b} scene · ${sh} inquadrature · ${l}`, people: "Persone",
    warnings: "Corretto automaticamente", produce: "Crea il video", producing: "Creazione…",
    steps: ["Leggi la fonte", "Copione", "Ritratti e voce", "Fotogrammi chiave", "Controllo immagini", "Movimento", "Bozza"],
    done: "La bozza è pronta", openHint: "Aprila dall'elenco delle bozze del progetto. Esporta con Handoff → Export.",
    fallback: "Inquadrature con zoom invece del movimento", missing: "Persone mostrate come sagoma (nessuna foto a licenza libera)",
    rerolled: (n) => `Il controllo immagini ha rifatto ${n} inquadratura/e.`, checkOk: "Controllo immagini: nessun problema",
    unverified: "Inquadrature ancora segnalate dopo il rifacimento (da controllare)",
    noProject: "Apri prima un progetto.", needUrl: "Inserisci un link alla fonte.",
    needText: "Incolla almeno 80 caratteri del testo della fonte.",
    noPython: "Python 3.9 o successivo non trovato. Esegui xcode-select --install nel Terminale e riprova.",
    noGeneration: "Questa versione di Selects non può generare media dalle app. Aggiorna Selects.",
    recent: "Lavori non finiti", resume: "Riprendi", dismiss: "Rimuovi dall'elenco", retry: "Riprova", elapsed: "Trascorso",
    noMusic: "Non è stato possibile creare la musica; la bozza è senza musica.",
    macOnly: "Per ora questa app funziona solo su macOS.", noEngine: "Mancano alcuni file dell'app. Reinstallala dalla libreria dei plugin.",
    errors: { FETCH_FAILED: "Impossibile aprire il link.", NO_TEXT: "Nessun testo trovato nel link. Incolla il testo.",
      TEXT_TOO_SHORT: "Il testo della fonte è troppo corto.", NO_JSON: "Impossibile leggere il copione dalla risposta dell'IA. Riprova." },
  },
  pt: {
    sourceTitle: "Fonte", link: "Link", text: "Texto", url: "Link da fonte", body: "Texto da fonte",
    bodyPh: "Cole o título e o corpo", target: "Duração alvo", makePlan: "Criar roteiro",
    planning: "Criando roteiro…", planTitle: "Roteiro", redo: "Refazer roteiro",
    summary: (s, b, sh, l) => `Cerca de ${s} s · ${b} cenas · ${sh} planos · ${l}`, people: "Pessoas",
    warnings: "Corrigido automaticamente", produce: "Criar o vídeo", producing: "Criando…",
    steps: ["Ler a fonte", "Roteiro", "Retratos e voz", "Quadros-chave", "Verificação de imagens", "Movimento", "Rascunho"],
    done: "O rascunho está pronto", openHint: "Abra-o na lista de rascunhos do projeto. Exporte com Handoff → Export.",
    fallback: "Planos com zoom em vez de movimento", missing: "Pessoas mostradas como silhueta (sem foto de licença livre)",
    rerolled: (n) => `A verificação refez ${n} plano(s).`, checkOk: "Verificação de imagens: sem problemas",
    unverified: "Planos ainda apontados pela verificação após refeitos (vale conferir)",
    noProject: "Abra um projeto primeiro.", needUrl: "Insira um link da fonte.",
    needText: "Cole pelo menos 80 caracteres do texto da fonte.",
    noPython: "Python 3.9 ou posterior não foi encontrado. Execute xcode-select --install no Terminal e tente de novo.",
    noGeneration: "Esta versão do Selects não gera mídia a partir de apps. Atualize o Selects.",
    recent: "Trabalhos inacabados", resume: "Continuar", dismiss: "Remover da lista", retry: "Tentar de novo", elapsed: "Decorrido",
    noMusic: "Não foi possível criar a música; o rascunho está sem música.",
    macOnly: "Por enquanto, este app funciona apenas no macOS.", noEngine: "Faltam arquivos do app. Reinstale-o pela biblioteca de plugins.",
    errors: { FETCH_FAILED: "Não foi possível abrir o link.", NO_TEXT: "Nenhum texto encontrado no link. Cole o texto.",
      TEXT_TOO_SHORT: "O texto da fonte é curto demais.", NO_JSON: "Não foi possível ler o roteiro na resposta da IA. Tente de novo." },
  },
  tr: {
    sourceTitle: "Kaynak", link: "Bağlantı", text: "Metin", url: "Kaynak bağlantısı", body: "Kaynak metni",
    bodyPh: "Başlığı ve metni yapıştırın", target: "Hedef süre", makePlan: "Senaryo oluştur",
    planning: "Senaryo oluşturuluyor…", planTitle: "Senaryo", redo: "Senaryoyu yeniden oluştur",
    summary: (s, b, sh, l) => `Yaklaşık ${s} sn · ${b} sahne · ${sh} çekim · ${l}`, people: "Kişiler",
    warnings: "Otomatik düzeltildi", produce: "Videoyu oluştur", producing: "Oluşturuluyor…",
    steps: ["Kaynağı oku", "Senaryo", "Portreler ve seslendirme", "Anahtar kareler", "Görsel kontrolü", "Hareket", "Taslak"],
    done: "Taslak hazır", openHint: "Projenin taslak listesinden açabilirsiniz. Dışa aktarmak için Handoff → Export'u kullanın.",
    fallback: "Hareket yerine yakınlaştırma kullanılan çekimler", missing: "Silüet olarak gösterilen kişiler (serbest lisanslı fotoğraf yok)",
    rerolled: (n) => `Görsel kontrolü ${n} çekimi yeniden oluşturdu.`, checkOk: "Görsel kontrolü: sorun yok",
    unverified: "Yeniden oluşturulduktan sonra kontrolün hâlâ not düştüğü çekimler (göz atmanızı öneririz)",
    noProject: "Önce bir proje açın.", needUrl: "Bir kaynak bağlantısı girin.",
    needText: "En az 80 karakterlik kaynak metni yapıştırın.",
    noPython: "Python 3.9 veya üstü bulunamadı. Terminal'de xcode-select --install komutunu çalıştırıp tekrar deneyin.",
    noGeneration: "Bu Selects sürümü uygulamalardan medya üretemiyor. Selects'i güncelleyin.",
    recent: "Tamamlanmamış işler", resume: "Devam et", dismiss: "Listeden kaldır", retry: "Tekrar dene", elapsed: "Geçen süre",
    noMusic: "Müzik oluşturulamadı; taslakta müzik yok.",
    macOnly: "Bu uygulama şimdilik yalnızca macOS'ta çalışır.", noEngine: "Uygulamanın dosyaları eksik. Eklenti Kitaplığı'ndan yeniden yükleyin.",
    errors: { FETCH_FAILED: "Bağlantı açılamadı.", NO_TEXT: "Bağlantıda metin bulunamadı. Metni yapıştırın.",
      TEXT_TOO_SHORT: "Kaynak metni çok kısa.", NO_JSON: "Yapay zekâ yanıtından senaryo okunamadı. Tekrar deneyin." },
  },
};

const enc = (s: string) => new TextEncoder().encode(s);
const dec = (b: any) => new TextDecoder().decode(b);
const pq = (s: string) => "'" + String(s).replace(/'/g, "'\\''") + "'";
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function bytesToB64(u: Uint8Array): string {
  let s = "";
  for (let i = 0; i < u.length; i += 0x8000) s += String.fromCharCode.apply(null, Array.from(u.subarray(i, i + 0x8000)) as any);
  return btoa(s);
}
function extractJson(text: string): any {
  const s = String(text || "");
  const fence = s.match(/```(?:json)?\s*([\s\S]*?)```/);
  const body = fence ? fence[1] : s;
  const a = body.indexOf("{");
  const b = body.lastIndexOf("}");
  if (a < 0 || b <= a) throw new Error("NO_JSON");
  return JSON.parse(body.slice(a, b + 1));
}
function host(): any {
  try {
    return (window.parent as any)?.__DI__ || null;
  } catch (e) {
    return null;
  }
}
function hostFs(): any {
  const fs = host()?.FileSystem;
  const need = ["readFile", "writeFile", "homedir", "existsSync", "mkdirSync", "readdirSync"];
  return fs && need.every((k) => typeof fs[k] === "function") ? fs : null;
}
// Selects' own media generation for plug-in panels: billed to the user's Selects credits, results
// saved into a folder under ~/.selects/plugin-data (Selects 2.0.512+).
function generation(): any {
  const m = host()?.MediaGeneration;
  if (!m || typeof m.submit !== "function" || typeof m.list !== "function") return null;
  if (typeof m.isAvailable === "function" && !m.isAvailable()) return null;
  if (typeof m.supportsPluginFiles === "function" && !m.supportsPluginFiles()) return null;
  return m;
}
function languageName(code: string, ui: string): string {
  try {
    return new (Intl as any).DisplayNames([ui, "en"], { type: "language" }).of(code) || code;
  } catch (e) {
    return code;
  }
}

// ---- The AI judgments: script, picture plan, keyframe check ----
// Selects prefixes every panel request with a note to build with Selects tools, and caps a panel turn
// at five minutes. These requests need no tools, so each one says so first and last, and the script
// is asked for in two short turns rather than one long one.
const NO_TOOLS =
  "This request needs no tools. Do not call run_script, run_shell, a browser or any other tool, do not open links, and do not change the project. Answer directly with the JSON described below and nothing else.";

function scriptPrompt(art: any, f: any, target: number): string {
  const b = f.budget;
  return [
    NO_TOOLS,
    `You write Vox-style paper-collage explainer videos. From the source below, write the narration script for a vertical (9:16) explainer of about ${target} seconds.`,
    `[Language]\n- Write every spoken and on-screen word (narration, captions, headline, title, source_line) in ${f.language}, the source's language, in a ${f.style}.`,
    `[Length]\n- About ${b.beats} beats and about ${b.count} ${b.unit} of narration in total. Beat 1 is a hook that promises the point within 3 seconds.\n- Each beat's narration is 1-2 sentences. Use only facts from the source; names and numbers exactly as the source writes them.\n- End on the source's key meaning or contrast.`,
    `[Captions and titles]\n- captions: split the narration into subtitle lines of at most ${f.captionChars} characters; keep a person's name, and a number with its unit, on one line. Joining the lines with spaces must give the narration exactly (end-of-line punctuation may be dropped).\n- headline: the beat's on-screen headline, at most ${f.headlineChars} characters.\n- cut_word: the narration word, exactly as written, where a second picture can start, near the middle; an empty string when the narration is under 3 seconds.\n- title: the video title (at most 40 characters). source_line: "${f.sourceLabel} · outlet, date, author" with the date written the usual way in ${f.language}; leave out anything the source information lacks, and use an empty string if the outlet is unknown.`,
    `[People]\n- cast: real public figures from the source that the pictures will need (at most 8). key: lowercase English; name: full name in English; wiki: the English Wikipedia article title; wardrobe: their usual clothes, in English. Private individuals never go in cast.`,
    `JSON format:\n{"title": "...", "source_line": "...", "cast": [{"key": "...", "name": "...", "wiki": "...", "wardrobe": "..."}], "beats": [{"headline": "...", "narration": "...", "captions": ["..."], "cut_word": "..."}]}`,
    `Source information: title: ${art.title || ""} / standfirst: ${art.subtitle || art.description || ""} / outlet: ${art.source || ""} / date: ${art.date || ""} / author: ${art.byline || ""}`,
    `Text:\n${String(art.body || "").slice(0, 8000)}`,
    NO_TOOLS,
  ].join("\n\n");
}
function picturePrompt(script: any): string {
  const beats = (script.beats || []).map((b: any, i: number) => ({ beat: i + 1, headline: b.headline, narration: b.narration, twoShots: !!b.cut_word }));
  return [
    NO_TOOLS,
    "You design the pictures for a Vox-style paper-collage explainer whose script is below. For each beat, in the same order, give the background colour and the shots (2 shots when twoShots is true, otherwise 1).",
    "[Pictures]\n- scene: in English, the concrete paper-collage objects and their layout that show the narration. Draw no person other than the cast (write 'faceless paper silhouettes' if people are unavoidable).\n- Words in the picture are short English capitals only, always in single quotes (e.g. a place card 'TRUMP'). No big title banner and no logos; companies appear as words only.\n- Say which person a label belongs to (e.g. under Jensen Huang's feet a stamp 'TAIWAN').\n- element_motion: in English, a simple movement of one or two elements; keep shots with words especially simple.\n- camera: one of push_in, pull_out, parallax, pan, static. Shots with people use only push_in, parallax or static. Neighbouring shots differ.\n- cast: keys from the cast list below, at most 4 per shot, only people the shot shows.\n- bg: the beat's background colour in English; neighbouring beats differ.",
    `Cast: ${JSON.stringify(script.cast || [])}`,
    `Script: ${JSON.stringify(beats)}`,
    'JSON format:\n{"beats": [{"bg": "...", "shots": [{"scene": "...", "element_motion": "...", "camera": "...", "cast": ["key"]}]}]}',
    NO_TOOLS,
  ].join("\n\n");
}
function shortenPrompt(raw: any, f: any, target: number, seconds: number): string {
  const cut = Math.round((1 - target / seconds) * 100);
  return `${NO_TOOLS}\n\nThis explainer script reads for about ${seconds} seconds but must fit ${target} seconds. Shorten the narration by about ${cut}% (fewer words per beat, or drop the weakest beat), keep it in ${f.language}, keep every other field and rule, and make each beat's captions match its new narration exactly. Answer with the whole JSON in the same format.\n\n${JSON.stringify(raw)}`;
}
function repairPrompt(raw: string, errors: string[]): string {
  return `${NO_TOOLS}\n\nThis script JSON has problems: ${errors.join("; ")}. Answer with the corrected JSON only, in the same format.\n\n${raw}`;
}
function checkPrompt(expect: any[]): string {
  return [
    NO_TOOLS,
    "These images are video keyframes; each tile's shot number (e.g. 1a) is at its top left. Compare them with the expectations below and pick only the shots that must be remade.",
    "Remake a shot only for one of these problems.\npeople: it shows a person who is not in people (photo-like people count; faceless paper silhouettes are fine), a person from people is missing, a face was redrawn as a cartoon instead of a photo, or a label (a country, a name) sits next to the wrong person.\ntext: a word from words is misspelled, garbled or cut off, or there is readable nonsense lettering (letters that form no real word).\nExtra correctly spelled words, where text sits, and differences of style are fine.",
    `Expectations: ${JSON.stringify(expect)}`,
    'Answer with JSON only: {"reroll": [{"shot": "1a", "kind": "people or text", "reason": "one sentence"}]}',
  ].join("\n\n");
}

const EDIT_HEAD = [
  { key: "text", label: "Headline", type: "text", defaultValue: "" },
  { key: "fontSize", label: "Size", type: "number", defaultValue: 92, min: 40, max: 140, step: 1 },
  { key: "fontFamily", label: "Font", type: "text", defaultValue: "" },
  { key: "barColor", label: "Bar color", type: "color", defaultValue: "#141414" },
  { key: "textColor", label: "Text color", type: "color", defaultValue: "#F4ECDD" },
  { key: "accentColor", label: "Accent color", type: "color", defaultValue: "#D7261E" },
];
const EDIT_CAP = [
  { key: "text", label: "Caption", type: "text", defaultValue: "" },
  { key: "fontSize", label: "Size", type: "number", defaultValue: 56, min: 30, max: 100, step: 1 },
  { key: "fontFamily", label: "Font", type: "text", defaultValue: "" },
];
const EDIT_CREDIT = [
  { key: "source", label: "Source", type: "text", defaultValue: "" },
  { key: "photos", label: "Photo credits", type: "text", defaultValue: "" },
];

function draftScript(projectId: string, sel: any, ids: Record<string, string>): string {
  const segs = sel.segments.map((s: any) => ({ rid: ids[s.file], dur: s.dur }));
  const narr = sel.narration.map((n: any) => ({ rid: ids[n.file], start: n.start, dur: n.dur }));
  const music = sel.music ? ids[sel.music] : null;
  return `
const p = selects.project(${JSON.stringify(projectId)});
const d = await p.createDraft({ name: ${JSON.stringify(sel.draftName)} });
const segs = ${JSON.stringify(segs)};
for (const s of segs) await d.insertResource({ resourceId: s.rid, sourceRange: { startSeconds: 0, endSeconds: s.dur } });
await d.setFrameSize({ width: 1080, height: 1920 });
const meta = await d.meta();
const fps = meta.fps;
const F = (x: number) => Math.round(x * fps);
const main = await d.clips({ trackScope: "main" });
const total = main.reduce((a: number, c: any) => Math.max(a, c.endFrame), 0);
const narr = ${JSON.stringify(narr)};
for (const n of narr) {
  const a = F(n.start);
  await d.overlayResource({ resource: p.resource(n.rid), over: await d.rangeAtFrames(a, Math.min(total, a + Math.floor(n.dur * fps))) });
}
const music = ${JSON.stringify(music)};
if (music) {
  await d.overlayResource({ resource: p.resource(music), over: await d.rangeAtFrames(0, total) });
  const bc = (await d.clips({ trackScope: "all" })).find((c: any) => c.resourceId === music);
  if (bc) await d.setClipAudio({ clip: bc, volumeDb: ${MUSIC_DB}, fadeInSeconds: 0.4, fadeOutSeconds: 1.8 });
}
const TH = ${JSON.stringify(TPL.headline)};
const TC = ${JSON.stringify(TPL.caption)};
const TK = ${JSON.stringify(TPL.credit)};
for (const h of ${JSON.stringify(sel.headlines)}) {
  if (!h.text) continue;
  await d.addMotionGraphic({ label: "Headline " + h.beat, tsxCode: TH, parameters: { text: h.text, fontSize: h.size, fontFamily: "", barColor: "#141414", textColor: "#F4ECDD", accentColor: "#D7261E" }, editableParameters: ${JSON.stringify(EDIT_HEAD)} as any, within: await d.rangeAtFrames(F(h.start), Math.min(total, F(h.end))) });
}
let i = 0;
for (const c of ${JSON.stringify(sel.captions)}) {
  i += 1;
  const a = F(c.start), b = Math.min(total, F(c.end));
  if (b <= a) continue;
  await d.addMotionGraphic({ label: "Caption " + String(i).padStart(2, "0"), tsxCode: TC, parameters: { text: c.text, fontSize: 56, fontFamily: "", bottom: ${CAPTION_BOTTOM} }, editableParameters: ${JSON.stringify(EDIT_CAP)} as any, within: await d.rangeAtFrames(a, b) });
}
const cr = ${JSON.stringify(sel.credit)};
if (cr.source || cr.photos) {
  await d.addMotionGraphic({ label: "Source credit", tsxCode: TK, parameters: { source: cr.source, photos: cr.photos, top: 1560 }, editableParameters: ${JSON.stringify(EDIT_CREDIT)} as any, within: await d.rangeAtFrames(Math.min(F(cr.start), total - 1), total) });
}
const out = await d.commitAll("Vox-style explainer");
return { draftId: (out as any).createdDraftId ?? null, seconds: total / fps, clips: main.length };
`;
}

export default function Panel({ sdk, context, ui }: any) {
  const uiLang = String(context?.language || "en").split("-")[0];
  const S: Strings = STRINGS[uiLang] ?? STRINGS.en;
  const projectId: string | null = context?.projectId ?? null;
  const fs = React.useMemo(() => hostFs(), []);

  const [mode, setMode] = React.useState<"link" | "text">("link");
  const [url, setUrl] = React.useState("");
  const [text, setText] = React.useState("");
  const [target, setTarget] = React.useState(55);
  const [busy, setBusy] = React.useState<string | null>(null);
  const [error, setError] = React.useState("");
  const [status, setStatus] = React.useState("");
  const [step, setStep] = React.useState(-1);
  const [job, setJob] = React.useState<any>(null); // { id, dir }
  const [plan, setPlan] = React.useState<any>(null);
  const [check, setCheck] = React.useState<any>(null); // validate result
  const [result, setResult] = React.useState<any>(null);
  const [jobs, setJobs] = React.useState<any[]>([]);
  const [t0, setT0] = React.useState(0);
  const [, tick] = React.useState(0);
  const env = React.useRef<any>(null);

  React.useEffect(() => {
    if (!busy) return;
    const h = setInterval(() => tick((x) => x + 1), 1000);
    return () => clearInterval(h);
  }, [busy]);

  const errText = (e: any) => {
    const m = String(e?.message || e || "");
    return S.errors[m] || m;
  };

  // ---- Host helpers ----
  const shell = async (command: string, summary: string, timeoutMs = 120000) => {
    const r: any = await sdk.runShell({ summary, command, timeoutMs, maxOutputBytes: 48000 });
    return { ...r, stdout: String(r.stdout || ""), stderr: String(r.stderr || ""), output: String(r.output || "") };
  };
  async function home(): Promise<string> {
    if (fs) return fs.homedir();
    return (await shell(`printf %s "$HOME"`, "Find home folder")).stdout.trim();
  }
  async function readText(path: string): Promise<string | null> {
    if (fs) {
      try {
        return fs.existsSync(path) ? dec(await fs.readFile(path)) : null;
      } catch (e) {
        return null;
      }
    }
    const r = await shell(`[ -f ${pq(path)} ] && cat ${pq(path)}`, "Read job file");
    return r.exitCode === 0 ? r.stdout : null;
  }
  async function writeBytes(path: string, bytes: Uint8Array) {
    if (fs) {
      const dir = path.slice(0, path.lastIndexOf("/"));
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      await fs.writeFile(path, bytes);
      return;
    }
    const b64 = bytesToB64(bytes);
    await shell(`mkdir -p ${pq(path.slice(0, path.lastIndexOf("/")))} && : > ${pq(path + ".b64")}`, "Prepare file");
    for (let i = 0; i < b64.length; i += 60000) await shell(`printf %s ${pq(b64.slice(i, i + 60000))} >> ${pq(path + ".b64")}`, "Write file");
    await shell(`base64 -D -i ${pq(path + ".b64")} -o ${pq(path)} && rm ${pq(path + ".b64")}`, "Write file");
  }
  async function readB64(path: string): Promise<string> {
    if (fs) return bytesToB64(new Uint8Array(await fs.readFile(path)));
    const size = parseInt((await shell(`stat -f%z ${pq(path)}`, "Read image")).stdout.trim(), 10) || 0;
    let s = "";
    for (let i = 0; i * 30000 < size; i++) s += (await shell(`dd if=${pq(path)} bs=30000 skip=${i} count=1 2>/dev/null | base64`, "Read image")).stdout.replace(/\s+/g, "");
    return s;
  }
  const readJson = async (path: string) => {
    const t = await readText(path);
    try {
      return t ? JSON.parse(t) : null;
    } catch (e) {
      return null;
    }
  };
  const writeJson = (path: string, v: any) => writeBytes(path, enc(JSON.stringify(v)));

  // Working files live in ~/.selects/plugin-data/vox-explainer; the engine in the plugin's skills folder.
  async function ensureEnv() {
    if (env.current) return env.current;
    if (IS_WIN) throw new Error(S.macOnly);
    const root = `${await home()}/.selects/plugin-data/${APP_ID}`;
    const r = await shell(
      `[ -f ${ENGINE} ] || { echo NO_ENGINE; exit 0; }; for p in /opt/homebrew/bin/python3 /usr/local/bin/python3 /usr/bin/python3; do if [ -x "$p" ] && "$p" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)' 2>/dev/null; then echo "$p"; break; fi; done`,
      "Find the engine and Python"
    );
    const py = r.stdout.trim().split("\n")[0];
    if (py === "NO_ENGINE") throw new Error(S.noEngine);
    if (!py) throw new Error(S.noPython);
    env.current = { root, py };
    return env.current;
  }
  async function run(cmd: string, dir: string, extra = "", summary = "") {
    const e = await ensureEnv();
    const r = await shell(`${pq(e.py)} ${ENGINE} ${cmd} ${pq(dir)}${extra ? " " + extra : ""}`, summary || `Vox explainer: ${cmd}`, 280000);
    let j: any = null;
    try {
      j = JSON.parse(r.stdout.trim().split("\n").pop() || "");
    } catch (err) {}
    if (!j) throw new Error((r.stderr || r.output || "engine failed").slice(-800));
    if (!j.ok && j.error) throw new Error(String(j.error));
    return j;
  }

  // A panel AI turn is capped at five minutes; a timed-out turn is tried once more.
  async function ask(prompt: string, images?: any[]) {
    for (let attempt = 0; ; attempt++) {
      try {
        const r = await sdk.askAI({ prompt, timeoutMs: 300000, ...(images ? { images } : {}) });
        return extractJson(r.text);
      } catch (err: any) {
        if (attempt === 0 && /did not finish|timed? ?out/i.test(String(err?.message || err))) continue;
        throw err;
      }
    }
  }

  // ---- Selects generation: submit the engine's requests, wait for the files ----
  async function scope() {
    const r: any = await sdk.runScript({ summary: "Read the open Project", script: "const s = await selects.editor.state(); return { libraryId: s.libraryId, projectId: s.projectId };" });
    if (r.isError || !r.result?.libraryId) throw new Error(String(r.output || "no library").slice(0, 400));
    if (r.result.projectId !== projectId) throw new Error(S.noProject);
    return { libraryId: r.result.libraryId, projectId: r.result.projectId };
  }
  // gen.json lists every request (by key) and the file Selects delivered for it; the engine reads it.
  // One in-memory copy per run; writes are queued so parallel generations never overwrite each other.
  type Store = { dir: string; gen: any; chain: Promise<void> };
  const persist = (st: Store) => (st.chain = st.chain.then(() => writeJson(`${st.dir}/gen.json`, st.gen)));
  async function generate(st: Store, sc: any, reqs: any[], label: string, onFail: "throw" | "keep" = "throw") {
    const m = generation();
    if (!m) throw new Error(S.noGeneration);
    const gen = st.gen;
    const pending: any[] = [];
    for (const q of reqs) {
      const cur = gen[q.gen];
      if (cur && (cur.attempt || 1) > (q.attempt || 1)) {
        if (!cur.path && !cur.failed) pending.push(q); // a newer remake is in flight; wait for that one
        continue;
      }
      if (cur && cur.key === q.key && cur.path) continue;
      if (!cur || cur.key !== q.key || !cur.jobId) {
        // The key makes a resubmit after a reload resolve to the same job instead of generating again.
        const res = await m.submit({
          origin: { tool: q.tool, tab: "plugin", recipeId: APP_ID }, scope: sc, key: q.key, modelId: q.modelId, input: q.input,
          uploads: Object.fromEntries(Object.entries(q.uploads || {}).map(([k, p]) => [k, { pluginFile: p }])),
          outputName: q.outputName, batch: 1, delivery: { pluginFolder: q.folder },
        });
        gen[q.gen] = { key: q.key, attempt: q.attempt, jobId: res.jobIds[0] };
        await persist(st);
      }
      pending.push(q);
    }
    const failed: any[] = [];
    const retried = new Set<string>();
    const deadline = Date.now() + 45 * 60 * 1000;
    let left = pending.slice();
    while (left.length) {
      if (Date.now() > deadline) {
        for (const q of left) {
          failed.push({ ...q, errorCode: "timeout" });
          gen[q.gen] = { ...gen[q.gen], failed: "timeout" };
        }
        break;
      }
      const list: any[] = (await m.list(sc)) || [];
      const byId = new Map(list.map((j: any) => [j.jobId, j]));
      const next: any[] = [];
      for (const q of left) {
        const entry = gen[q.gen];
        const j: any = byId.get(entry.jobId);
        const path = j?.outputs?.find((o: any) => o.path)?.path;
        if (j && j.deliveryStatus === "delivered" && path) {
          gen[q.gen] = { ...entry, path };
        } else if (j && j.deliveryStatus === "download_failed" && !retried.has(entry.jobId) && typeof m.retryDelivery === "function") {
          retried.add(entry.jobId);
          await m.retryDelivery(sc, entry.jobId);
          next.push(q);
        } else if (j && /fail|error|reject|cancel|refus|block/i.test(String(j.status)) && j.deliveryStatus !== "downloading") {
          failed.push({ ...q, errorCode: j.errorCode || j.status });
          gen[q.gen] = { ...entry, failed: j.errorCode || j.status };
        } else {
          next.push(q);
        }
      }
      await persist(st);
      if (label) setStatus(`${label} · ${pending.length - next.length - failed.length + (reqs.length - pending.length)}/${reqs.length}`);
      left = next;
      if (left.length) await sleep(4000);
    }
    await persist(st);
    if (failed.length && onFail === "throw") throw new Error(`${label}: ${failed.map((f) => `${f.id || f.gen} ${f.errorCode}`).join(", ")}`);
    return failed;
  }

  const loadJobs = React.useCallback(async () => {
    if (!projectId || !fs) return;
    try {
      const root = `${fs.homedir()}/.selects/plugin-data/${APP_ID}/jobs`;
      if (!fs.existsSync(root)) return setJobs([]);
      const list: any[] = [];
      for (const n of fs.readdirSync(root)) {
        const j = await readJson(`${root}/${n}/job.json`);
        const pj = (await readJson(`${root}/${n}/panel.json`)) || {};
        if (j && j.projectId === projectId && pj.started && !pj.done && !pj.dismissed)
          list.push({ id: j.id, dir: `${root}/${n}`, title: pj.title || j.input?.url || j.id, updated: j.updated || "" });
      }
      setJobs(list.sort((a, b) => String(b.updated).localeCompare(String(a.updated))).slice(0, 5));
    } catch (e) {}
  }, [projectId, fs]);
  React.useEffect(() => {
    loadJobs();
  }, [loadJobs]);

  async function savePanel(dir: string, patch: any) {
    const cur = (await readJson(`${dir}/panel.json`)) || {};
    const next = { ...cur, ...patch };
    await writeJson(`${dir}/panel.json`, next);
    return next;
  }

  // ---- 1. Script ----
  async function makePlan() {
    setError("");
    setResult(null);
    setPlan(null);
    if (!projectId) return setError(S.noProject);
    if (mode === "link" && !/^https?:\/\//.test(url.trim())) return setError(S.needUrl);
    if (mode === "text" && text.trim().length < 80) return setError(S.needText);
    setBusy("plan");
    setT0(Date.now());
    try {
      const e = await ensureEnv();
      const id = `vx${Date.now().toString(36)}`;
      const dir = `${e.root}/jobs/${id}`;
      const input = mode === "link" ? { kind: "link", url: url.trim() } : { kind: "text", text: text.trim() };
      await writeJson(`${dir}/job.json`, { id, projectId, created: new Date().toISOString(), input, target, stage: "new" });
      setJob({ id, dir });
      setStep(0);
      setStatus(S.steps[0]);
      const f = await run("fetch", dir, "", "Read the source");
      const art = await readJson(`${dir}/article.json`);
      setStep(1);
      setStatus(`${S.steps[1]} · ${f.title || ""}`);
      const script = await ask(scriptPrompt(art, f, target));
      setStatus(`${S.steps[1]} · ${f.title || ""} · 2/2`);
      const pics = await ask(picturePrompt(script));
      let parsed: any = { ...script, beats: (script.beats || []).map((bt: any, i: number) => ({ ...bt, ...((pics.beats || [])[i] || {}) })) };
      await writeJson(`${dir}/plan.json`, parsed);
      let v = await run("validate", dir, "", "Check the script");
      if (!v.ok) {
        parsed = await ask(repairPrompt(JSON.stringify(parsed), v.errors || []));
        await writeJson(`${dir}/plan.json`, parsed);
        v = await run("validate", dir, "", "Check the script");
        if (!v.ok) throw new Error((v.errors || []).join("; "));
      }
      if (v.seconds > target * 1.15) {
        // LESSON: the first English run read 27% long; fix the length before any narration is paid for.
        setStatus(`${S.steps[1]} · ${v.seconds}s → ${target}s`);
        parsed = await ask(shortenPrompt(parsed, f, target, v.seconds));
        await writeJson(`${dir}/plan.json`, parsed);
        const v2 = await run("validate", dir, "", "Check the script");
        if (v2.ok) v = v2;
      }
      const p = await readJson(`${dir}/plan.json`);
      setPlan(p);
      setCheck(v);
      await savePanel(dir, { title: p?.title || f.title });
      setStep(-1);
      setStatus("");
    } catch (err: any) {
      setError(errText(err));
    } finally {
      setBusy(null);
    }
  }

  // ---- 2. Everything else, resumable ----
  async function produce(resume?: any) {
    setError("");
    const j0 = resume || job;
    if (!j0) return;
    if (!projectId) return setError(S.noProject);
    setBusy("make");
    setT0(Date.now());
    setJob(j0);
    const dir = j0.dir;
    try {
      if (!generation()) throw new Error(S.noGeneration);
      let pj = await savePanel(dir, { started: true });
      if (!plan || resume) setPlan(await readJson(`${dir}/plan.json`));
      const sc = await scope();
      const st: Store = { dir, gen: (await readJson(`${dir}/gen.json`)) || {}, chain: Promise.resolve() };

      setStep(2);
      setStatus(S.steps[2]);
      if (!pj.portraits) pj = await savePanel(dir, { portraits: (await run("portraits", dir, "", "Find free-licence portraits")).missing || [] });
      await generate(st, sc, (await run("requests", dir, "narration", "Narration requests")).requests, S.steps[2]);
      if (!pj.timed) pj = await savePanel(dir, { timed: (await run("timeline", dir, "", "Narration timing")).seconds });
      const music = (await run("requests", dir, "music", "Music request")).requests;
      const musicDone = generate(st, sc, music, "", "keep").catch(() => [{ gen: "music" }]); // runs alongside

      setStep(3);
      await generate(st, sc, (await run("requests", dir, "keyframes", "Keyframe requests")).requests, S.steps[3], "keep");
      const gen = st.gen;
      const bad = Object.keys(gen).filter((k) => k.startsWith("kf:") && gen[k].failed).map((k) => k.slice(3));
      if (bad.length) {
        const attempt = Math.max(...bad.map((s) => gen["kf:" + s].attempt || 1)) + 1;
        await generate(st, sc, (await run("requests", dir, `keyframes ${pq(bad.join(","))} --attempt ${attempt}`, "Keyframe retries")).requests, S.steps[3]);
      }

      if (!pj.checked) {
        // Up to two AI check rounds; flagged shots are remade, the second round looks only at those.
        setStep(4);
        setStatus(S.steps[4]);
        let only: string[] = [];
        const rerolled: string[] = [];
        let remaining: any[] = [];
        for (let round = 0; round < 2; round++) {
          const sh = await run("sheet", dir, only.length ? pq(only.join(",")) : "", "Contact sheet");
          const images: any[] = [];
          for (const s of sh.sheets.slice(0, 4)) images.push({ dataUrl: `data:image/jpeg;base64,${await readB64(s.path)}`, name: s.shots.join(",") });
          let flagged: any[] = [];
          try {
            const ids = new Set(sh.expect.map((x: any) => x.shot));
            flagged = ((await ask(checkPrompt(sh.expect), images)).reroll || []).filter((x: any) => ids.has(String(x.shot)));
          } catch (err) {
            flagged = []; // the check is advisory; a failed check never blocks the video
          }
          remaining = flagged;
          // Round 2 remakes only people problems (the serious kind); text leftovers become notes.
          const eligible = round === 0 ? flagged : flagged.filter((x: any) => String(x.kind || "").startsWith("people"));
          const redo = eligible.map((x: any) => String(x.shot)).slice(0, Math.max(1, Math.ceil(sh.expect.length / 2)));
          if (!redo.length) break;
          if (round === 1) remaining = flagged.filter((x: any) => !redo.includes(String(x.shot)));
          const attempt = Math.max(...redo.map((s: string) => gen["kf:" + s]?.attempt || 1)) + 1;
          await generate(st, sc, (await run("requests", dir, `keyframes ${pq(redo.join(","))} --attempt ${attempt}`, "Remake keyframes")).requests, S.steps[4], "keep");
          rerolled.push(...redo);
          only = redo;
        }
        pj = await savePanel(dir, { checked: true, rerolled: Array.from(new Set(rerolled)),
          unverified: remaining.map((x: any) => `${x.shot} (${x.reason || ""})`) });
      }

      setStep(5);
      const failedClips = await generate(st, sc, (await run("requests", dir, "clips", "Motion requests")).requests, S.steps[5], "keep");
      if (failedClips.length) {
        // LESSON: a refused clip is refused again on every retry; the pan-and-zoom fallback is immediate.
        const ids = failedClips.map((f) => f.id);
        const kb = await run("kenburns", dir, pq(ids.join(",")), "Zoom fallback");
        for (const [sid, path] of Object.entries(kb.clips || {})) gen["clip:" + sid] = { ...(gen["clip:" + sid] || {}), path, fallback: true };
        await persist(st);
        pj = await savePanel(dir, { fallback: ids });
      }
      const musicFailed = await musicDone;
      if (musicFailed.length) pj = await savePanel(dir, { noMusic: true });

      setStep(6);
      setStatus(S.steps[6]);
      if (!pj.draftId) {
        const sel = await run("assembly", dir, "", "Plan the Draft");
        const files = JSON.stringify(sel.files);
        const imp: any = await sdk.runScript({
          summary: "Import the explainer media",
          allowCommit: true,
          script: `const p = selects.project(${JSON.stringify(projectId)});
const want = ${files};
const have = new Set((await p.resources()).map((r: any) => r.name));
const need = want.filter((f: string) => !have.has(f.split("/").pop()));
if (need.length) await p.importFiles({ paths: need });
return { imported: need.length };`,
        });
        if (imp.isError) throw new Error(String(imp.output || "import failed").slice(0, 800));
        let ids: any = null;
        for (let t = 0; t < 12 && !ids; t++) {
          const mres: any = await sdk.runScript({
            summary: "Find the imported media",
            script: `const rows = await selects.project(${JSON.stringify(projectId)}).resources();
const map: any = {};
for (const f of ${files}) {
  const r = rows.find((x: any) => x.name === f.split("/").pop());
  if (!r || r.durationSeconds == null) return { map: null };
  map[f] = r.resourceId;
}
return { map };`,
          });
          if (mres.isError) throw new Error(String(mres.output || "import failed").slice(0, 800));
          ids = mres.result?.map || null;
          if (!ids) await sleep(1500);
        }
        if (!ids) throw new Error("imported media did not become ready");
        const b: any = await sdk.runScript({ summary: "Build the explainer Draft", allowCommit: true, script: draftScript(projectId, sel, ids) });
        if (b.isError || !b.result?.draftId) throw new Error(String(b.output || "draft failed").slice(0, 800));
        pj = await savePanel(dir, { draftId: b.result.draftId, seconds: b.result.seconds, done: true });
      }
      const jd = (await readJson(`${dir}/job.json`)) || {};
      setResult({ seconds: pj.seconds, fallback: pj.fallback || [], rerolled: pj.rerolled || [], unverified: pj.unverified || [],
        noMusic: !!pj.noMusic, missing: Object.values(jd.portraits || {}).filter((v: any) => !v.ok).map((v: any) => v.name) });
      setStep(7);
      setStatus("");
      loadJobs();
    } catch (err: any) {
      setError(errText(err));
    } finally {
      setBusy(null);
    }
  }

  async function dismiss(j: any) {
    await savePanel(j.dir, { dismissed: true });
    loadJobs();
  }

  const secs = busy && t0 ? Math.round((Date.now() - t0) / 1000) : 0;

  return (
    <ui.Stack gap={16}>
      {IS_WIN && <ui.Message tone="error">{S.macOnly}</ui.Message>}
      <ui.Section title={S.sourceTitle}>
        <ui.Tabs
          value={mode}
          onChange={(v: "link" | "text") => !busy && setMode(v)}
          tabs={[
            { value: "link", label: S.link, content: <ui.TextField label={S.url} value={url} onChange={setUrl} placeholder="https://…" disabled={!!busy} /> },
            { value: "text", label: S.text, content: <ui.TextField label={S.body} value={text} onChange={setText} placeholder={S.bodyPh} multiline disabled={!!busy} /> },
          ]}
        />
        <ui.NumberField label={S.target} value={target} onChange={(v: number) => setTarget(Math.max(20, Math.min(120, Math.round(v))))} min={20} max={120} step={5} unit="s" disabled={!!busy} />
        <ui.Actions>
          <ui.Button variant={plan ? "secondary" : "primary"} busy={busy === "plan"} busyLabel={S.planning} disabled={!!busy || IS_WIN} onClick={makePlan}>
            {plan ? S.redo : S.makePlan}
          </ui.Button>
        </ui.Actions>
      </ui.Section>

      {plan && (
        <ui.Section title={`${S.planTitle}${plan.title ? " · " + plan.title : ""}`}>
          {check && (
            <p>
              {S.summary(check.seconds, check.beats, check.shots, languageName(plan.lang, uiLang))}
              {check.people?.length ? ` · ${S.people}: ${check.people.join(", ")}` : ""}
            </p>
          )}
          <div style={{ overflowX: "auto" }}>
            <table>
              <tbody>
                {plan.beats.map((b: any) => (
                  <tr key={b.n}>
                    <td style={{ verticalAlign: "top" }}>
                      <b>
                        {b.n}. {b.title}
                      </b>
                      <br />
                      <small>{b.narration}</small>
                    </td>
                    <td style={{ verticalAlign: "top" }}>
                      <small>{b.shots.map((s: any) => s.id).join(" · ")}</small>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {check?.warnings?.length > 0 && <ui.Message tone="muted">{S.warnings}: {check.warnings.join(" / ")}</ui.Message>}
          <ui.Actions>
            <ui.Button variant="primary" busy={busy === "make"} busyLabel={S.producing} disabled={!!busy || !!result} onClick={() => produce()}>
              {S.produce}
            </ui.Button>
          </ui.Actions>
        </ui.Section>
      )}

      {(busy || (step >= 0 && !error)) && step < 7 && (
        <ui.Section title={S.producing}>
          <ui.Progress steps={S.steps} current={Math.max(0, step)} />
          {status && (
            <ui.Message tone="muted">
              {status}
              {busy ? ` · ${S.elapsed} ${secs}s` : ""}
            </ui.Message>
          )}
        </ui.Section>
      )}

      {result && (
        <ui.Section title={S.done}>
          {result.seconds ? <ui.Message tone="success">{Math.round(result.seconds * 10) / 10}s</ui.Message> : null}
          <small>{S.openHint}</small>
          <small>{result.rerolled.length ? S.rerolled(result.rerolled.length) : S.checkOk}</small>
          {result.unverified.length > 0 && (
            <small>
              {S.unverified}: {result.unverified.join(" / ")}
            </small>
          )}
          {result.fallback.length > 0 && (
            <small>
              {S.fallback}: {result.fallback.join(", ")}
            </small>
          )}
          {result.missing.length > 0 && (
            <small>
              {S.missing}: {result.missing.join(", ")}
            </small>
          )}
          {result.noMusic && <small>{S.noMusic}</small>}
        </ui.Section>
      )}

      {error && (
        <ui.Section title="⚠">
          <ui.Message tone="error">{error}</ui.Message>
          {job && !busy && (
            <ui.Actions>
              <ui.Button variant="secondary" onClick={() => (plan ? produce(job) : makePlan())}>
                {S.retry}
              </ui.Button>
            </ui.Actions>
          )}
        </ui.Section>
      )}

      {jobs.length > 0 && !busy && (
        <ui.Section title={S.recent}>
          {jobs.map((j) => (
            <ui.Row key={j.id} align="center">
              <small style={{ minWidth: 0, flex: 1 }}>{j.title}</small>
              <ui.Button variant="ghost" onClick={() => produce(j)}>
                {S.resume}
              </ui.Button>
              <ui.IconButton icon="close" label={S.dismiss} onClick={() => dismiss(j)} />
            </ui.Row>
          ))}
        </ui.Section>
      )}
    </ui.Stack>
  );
}
