// Builds panel.tsx from src/ and engine/:
//   1. src/mg/sceneRuntimeSource.ts     the scene runtime (engine/runtime/SceneRuntime.tsx) as a string constant, which
//                                       each scene's Motion Graphic installs
//   2. src/stages/plan/promptSource.ts  the planning prompt, guide and schema (engine/prompt/*.md)
//   3. src/lint/glyphTable.ts           the lint's glyph table from the packaged fonts (tools/glyph-table.mjs)
//   4. panel.tsx                        one esbuild bundle of src/Panel.tsx that imports only react
// usage: node build.mjs [path/to/esbuild]   (ESBUILD also names it; PANEL_OUT and PANEL_NAME override the output and name)
import { createHash } from "node:crypto";
import { readFileSync, statSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { writeGlyphTable } from "./tools/glyph-table.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const spec = process.argv[2] || process.env.ESBUILD || "esbuild";
const esbuild = require(spec.startsWith(".") ? resolve(spec) : spec);
const manifest = JSON.parse(readFileSync(join(ROOT, "plugin.json"), "utf8"));
const panelOut = process.env.PANEL_OUT ? resolve(process.env.PANEL_OUT) : join(ROOT, "panel.tsx");
const name = process.env.PANEL_NAME || manifest.name;
const ALLOWED_IMPORTS = new Set(["react", "react/jsx-runtime"]);
const sha256 = (text) => createHash("sha256").update(text, "utf8").digest("hex");

function writeIfChanged(path, text) {
  let old = null;
  try {
    old = readFileSync(path, "utf8");
  } catch {}
  if (old !== text) writeFileSync(path, text);
}

// 1. the scene runtime
{
  const text = readFileSync(join(ROOT, "engine", "runtime", "SceneRuntime.tsx"), "utf8");
  writeIfChanged(
    join(ROOT, "src", "mg", "sceneRuntimeSource.ts"),
    "// Generated by build.mjs from engine/runtime/SceneRuntime.tsx; do not edit.\n" +
      "export const SCENE_RUNTIME_TSX: string = " + JSON.stringify(text) + ";\n" +
      'export const SCENE_RUNTIME_SHA256 = "' + sha256(text) + '";\n',
  );
}

// 2. the planning prompt
{
  const lines = ["// Generated by build.mjs from engine/prompt/*.md; do not edit."];
  for (const [key, file] of Object.entries({ PROMPT: "PROMPT.md", DIRECTING: "DIRECTING.md", SCHEMA: "SCHEMA.md" })) {
    const text = readFileSync(join(ROOT, "engine", "prompt", file), "utf8");
    lines.push("export const " + key + " = " + JSON.stringify(text) + ";");
    lines.push("export const " + key + '_SHA256 = "' + sha256(text) + '";');
  }
  writeIfChanged(join(ROOT, "src", "stages", "plan", "promptSource.ts"), lines.join("\n") + "\n");
}

// 3. the glyph table
writeGlyphTable({ root: ROOT });

// 4. the panel
const header = [
  "// @name " + name,
  "// @icon wand",
  "// One click turns a talking-head draft into a new 9:16 EO-style short: tightened talk, speaker framing,",
  "// typographic scenes, pictures and B-roll, music and loudness, exported and checked.",
].join("\n");
const result = esbuild.buildSync({
  absWorkingDir: ROOT,
  entryPoints: [join(ROOT, "src", "Panel.tsx")],
  outfile: panelOut,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  external: [...ALLOWED_IMPORTS],
  jsx: "automatic",
  charset: "utf8",
  legalComments: "none",
  minify: false,
  metafile: true,
  logLevel: "warning",
  define: { __EO_PLUGIN_VERSION__: JSON.stringify(manifest.version) },
  banner: { js: header },
});
const imports = new Set();
for (const o of Object.values(result.metafile.outputs)) for (const i of o.imports || []) if (i.external) imports.add(i.path);
const bad = [...imports].filter((i) => !ALLOWED_IMPORTS.has(i));
if (bad.length) {
  console.error("The panel may import only react; it imports " + bad.join(", "));
  process.exit(1);
}
console.log("built", relative(process.cwd(), panelOut) || panelOut, statSync(panelOut).size, "bytes (EO Shorts " + manifest.version + ")");
