const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const src=fs.readFileSync(path.join(root,'panel.tsx'),'utf8');
let head=src.slice(src.indexOf('const VERSION='),src.indexOf('function Poster('));const helpers=src.slice(src.indexOf('function initialPickFiles('),src.indexOf('async function contactPacket('));let main=src.slice(src.indexOf('export default function PlaceCount('),src.indexOf(' const selected=story.places')).replace('export default function','function');main+='return {create,state:()=>ref.current};}';
const place=n=>({id:'p'+n,sourceLabel:'Place '+n,name:'Place '+n,description:'Open views and quiet corners.',included:true,phase:'ready',files:[{path:'/raw/'+n+'a.mp4',duration:8},{path:'/raw/'+n+'b.mp4',duration:8}],picks:[{path:'/raw/'+n+'a.mp4',start:1,end:6,cropX:.5,cropY:.5},{path:'/raw/'+n+'b.mp4',start:1,end:6,cropX:.5,cropY:.5}]});
const fixture={version:1,projectId:'project-one',id:'story-one',title:'A weekend, well spent.',subtitle:'A quieter perspective.',folder:'/raw',places:[place(1),place(2)],settings:{pace:'balanced',aspect:'portrait',intro:true,assist:false,sourceAudio:false,music:null,accent:'#d8c6aa'},job:null,notices:[]};
head=head.replace(/^const newStory=.*$/m,'const newStory=pid=>JSON.parse(JSON.stringify(fixture));');
let aiCalls=0,mutations=0,offline=false;const configs=[];const files={homedir:()=>'/fixture-user',join:path.join,dirname:path.dirname,mkdirSync:()=>{},exists:async()=>!offline,renameSync:()=>{},writeFile:async()=>{},pathToLocalURL:p=>p,readFile:async p=>Buffer.from(fs.readFileSync(path.join(root,path.basename(p))))};
const inventory=fixture.places.flatMap(p=>p.files.map((f,i)=>({type:'video',path:f.path,resourceId:'native-'+p.id+'-'+i,durationSeconds:f.duration,frameRate:30,frameSize:{width:1920,height:1080}})));
const storage=new Map();const sdk={call:async(name,pid)=>({owner:{libraryId:'library',projectId:pid}}),askAI:async()=>{aiCalls++;throw Error('Unexpected AI request');},runScript:async({summary,script,allowCommit})=>{assert.equal(allowCommit,true);mutations++;const match=script.match(/^const cfg\s*=\s*(.*);\n/);assert(match);const c=JSON.parse(match[1]);configs.push(c);assert.equal(c.projectId,'project-one');if(summary==='Assemble editable story')return {result:{sequenceId:'draft-test',regions:[{place:-1,startFrame:0,endFrame:72},{place:0,startFrame:72,endFrame:177},{place:1,startFrame:177,endFrame:282}],clipCount:5,fps:30,endFrame:282}};if(summary==='Style story titles')return {result:{sequenceId:'draft-test',graphics:3}};if(summary==='Finish editable story')return {result:{status:'ready',sequenceId:'draft-test',deepLinkUrl:'test-only-link',clipCount:5,graphicCount:3,audioCount:0,seconds:9.4}};throw Error(summary);}};
function instance(){const box={fixture,console,URL,Date,Math,JSON,Map,Set,Number,Object,Array,String,Promise,TextEncoder,TextDecoder,Uint8Array,setTimeout,clearTimeout,window:{parent:{__DI__:{FileSystem:files,ProjectFileTree:{listEnrichedFileTree:async()=>inventory}}},localStorage:{setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k)||null}},useState:v=>{const x=typeof v==='function'?v():v;return [x&&x.ready===false?{ready:true,message:''}:x,()=>{}];},useRef:v=>({current:v}),useEffect:()=>{}};vm.createContext(box);vm.runInContext(head+'\n'+helpers+'\n'+main+'\nglobalThis.make=PlaceCount;',box);return box.make({sdk,context:{projectId:'project-one'}});}
(async()=>{const app=instance();await app.create();assert.equal(aiCalls,0);assert.equal(mutations,3);assert.equal(app.state().job.status,'ready');assert.equal(configs[0].segments.length,5);assert.equal(configs[1].regions.length,3);assert.equal(configs[2].music,null);assert(configs[0].segments.every(s=>s.path.startsWith('/raw/')));offline=true;const n=mutations;await instance().create();assert.equal(mutations,n);console.log(JSON.stringify({singleClickCreatesNativeDraft:true,sourceClipsAndGraphicsSeparate:true,noAIForAssembly:true,noMusicDependency:true,offlineMediaBlocksBeforeMutation:true}));})().catch(e=>{console.error(e);process.exit(1)});
